import type { Customer, Bottle, Cast, VisitRecord, Reservation } from '@/types'

export const mockCasts: Cast[] = [
  { id: 'cast-1', name: '桜', ruby: 'さくら', memo: 'ナンバーワン。シャンパン担当。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-2', name: '愛', ruby: 'あい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-3', name: '蘭', ruby: 'らん', memo: '土日のみ出勤。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-4', name: '葵', ruby: 'あおい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-5', name: '凛', ruby: 'りん', memo: '新人。フォロー必要。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-6', name: '麻衣', ruby: 'まい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-7', name: '瑠璃', ruby: 'るり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-8', name: '奈々', ruby: 'なな', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-9', name: '彩花', ruby: 'あやか', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-10', name: '雪', ruby: 'ゆき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-11', name: '茉莉', ruby: 'まり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-12', name: '優香', ruby: 'ゆか', memo: '平日のみ。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-13', name: '心春', ruby: 'こはる', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-14', name: '結衣', ruby: 'ゆい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-15', name: '真琴', ruby: 'まこと', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-16', name: '里菜', ruby: 'りな', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-17', name: '詩織', ruby: 'しおり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-18', name: '華', ruby: 'はな', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-19', name: '千夏', ruby: 'ちなつ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-20', name: '明日香', ruby: 'あすか', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-21', name: '紬', ruby: 'つむぎ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-22', name: '柚希', ruby: 'ゆずき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-23', name: '朱里', ruby: 'あかり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-24', name: '美咲', ruby: 'みさき', memo: '週3出勤。人気急上昇中。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-25', name: '七海', ruby: 'ななみ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-26', name: '恵', ruby: 'めぐみ', memo: 'ベテラン。接客経験10年以上。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-27', name: '沙織', ruby: 'さおり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-28', name: '理沙', ruby: 'りさ', memo: '土日祝のみ出勤。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-29', name: '夏希', ruby: 'なつき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-30', name: '芽衣', ruby: 'めい', memo: '新人。丁寧な接客が好評。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-31', name: '千尋', ruby: 'ちひろ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-32', name: '由美', ruby: 'ゆみ', memo: 'ナンバー候補。歌が得意。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-33', name: '萌', ruby: 'もえ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-34', name: '陽菜', ruby: 'ひな', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-35', name: '花音', ruby: 'かのん', memo: '歌唱力が高い。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-36', name: '珠希', ruby: 'たまき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-37', name: '琴葉', ruby: 'ことは', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-38', name: '紗良', ruby: 'さら', memo: '週4出勤。接客安定。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-39', name: '初音', ruby: 'はつね', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-40', name: '彩乃', ruby: 'あやの', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-41', name: '澪', ruby: 'みお', memo: '落ち着いた雰囲気が人気。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-42', name: '鈴', ruby: 'すず', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-43', name: '望', ruby: 'のぞみ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-44', name: '穂香', ruby: 'ほのか', memo: '新人。元気が売り。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-45', name: '杏', ruby: 'あんず', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-46', name: '和香', ruby: 'わか', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-47', name: '小春', ruby: 'こはる', memo: '土日のみ。学生。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-48', name: '光', ruby: 'ひかり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-49', name: '桃花', ruby: 'ももか', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-50', name: '柊', ruby: 'ひいらぎ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-51', name: '藍', ruby: 'あい', memo: '落ち着いた接客スタイル。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-52', name: '茜', ruby: 'あかね', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-53', name: '涼', ruby: 'りょう', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-54', name: '美羽', ruby: 'みう', memo: '週3。ダンスが得意。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-55', name: '月', ruby: 'つき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-56', name: '星奈', ruby: 'せいな', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-57', name: '柚子', ruby: 'ゆず', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-58', name: '夕佳', ruby: 'ゆか', memo: 'ベテラン組。頼れるキャスト。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-59', name: '宙', ruby: 'そら', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-60', name: '玲', ruby: 'れい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-61', name: '彩', ruby: 'いろは', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-62', name: '美桜', ruby: 'みお', memo: '新人。研修中。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-63', name: '音羽', ruby: 'おとは', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-64', name: '紅葉', ruby: 'もみじ', memo: '秋からの新メンバー。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-65', name: '春菜', ruby: 'はるな', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-66', name: '白雪', ruby: 'しらゆき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-67', name: '夕凪', ruby: 'ゆうなぎ', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-68', name: '綺羅', ruby: 'きら', memo: 'ステージパフォーマンスが好評。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-69', name: '汐里', ruby: 'しおり', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-70', name: '水月', ruby: 'みつき', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-71', name: '優', ruby: 'ゆう', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-72', name: '詩', ruby: 'うた', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-73', name: '菜緒', ruby: 'なお', memo: '平日限定出勤。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-74', name: '舞', ruby: 'まい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-75', name: '胡蝶', ruby: 'こちょう', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-76', name: '真白', ruby: 'ましろ', memo: '週2。副業キャスト。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-77', name: '一花', ruby: 'いちか', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-78', name: '珊瑚', ruby: 'さんご', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-79', name: '暖', ruby: 'はる', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-80', name: '颯', ruby: 'そう', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-81', name: '蒼', ruby: 'あお', memo: 'クールな雰囲気が人気。', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-82', name: '紫苑', ruby: 'しおん', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
  { id: 'cast-83', name: '流星', ruby: 'りゅうせい', memo: '', updatedAt: '2026-03-23', updatedBy: '' },
]

export const mockCustomers: Customer[] = [
  { id: 'customer-1', name: '田中 一郎', ruby: 'たなか いちろう', nickname: 'たなちゃん', designatedCastIds: ['cast-1'], isAlert: false, alertReason: '', memo: 'VIPクライアント。高級シャンパン好み。', linkedCustomerIds: ['customer-4'], lastVisitDate: '2026-03-16', updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '田中様専用グラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-2', name: '鈴木 健太', ruby: 'すずき けんた', nickname: 'すーさん', designatedCastIds: ['cast-2'], isAlert: true, alertReason: '無断キャンセル2回。支払いトラブルあり。', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-02', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-3', name: '佐藤 大輔', ruby: 'さとう だいすけ', nickname: 'だいちゃん', designatedCastIds: [], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-02-16', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-4', name: '山田 誠', ruby: 'やまだ まこと', nickname: 'やまちゃん', designatedCastIds: ['cast-1', 'cast-2'], isAlert: false, alertReason: '', memo: 'ウィスキー好み。田中様の紹介。', linkedCustomerIds: ['customer-1'], lastVisitDate: '2026-03-09', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-5', name: '伊藤 浩', ruby: 'いとう ひろし', nickname: 'いとちゃん', designatedCastIds: ['cast-3'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-26', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-6', name: '渡辺 真一', ruby: 'わたなべ しんいち', nickname: 'わたちゃん', designatedCastIds: ['cast-4'], isAlert: false, alertReason: '', memo: '誕生日：3月15日。', linkedCustomerIds: [], lastVisitDate: '2026-01-22', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-7', name: '中村 拓也', ruby: 'なかむら たくや', nickname: 'なかちゃん', designatedCastIds: ['cast-5'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-09-24', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-8', name: '小林 雄二', ruby: 'こばやし ゆうじ', nickname: 'こばちゃん', designatedCastIds: ['cast-6'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2024-11-08', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-9', name: '加藤 翔太', ruby: 'かとう しょうた', nickname: 'かとちゃん', designatedCastIds: ['cast-7'], isAlert: false, alertReason: '', memo: 'シャンパン好み。毎月来店。', linkedCustomerIds: [], lastVisitDate: '2026-03-20', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-10', name: '吉田 悠', ruby: 'よしだ はるか', nickname: 'よしちゃん', designatedCastIds: ['cast-8'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-23', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-11', name: '山口 蓮', ruby: 'やまぐち れん', nickname: 'やまぐちちゃん', designatedCastIds: ['cast-9'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-07', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-12', name: '松本 律', ruby: 'まつもと りつ', nickname: 'まつちゃん', designatedCastIds: ['cast-10'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-09-04', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-13', name: '井上 颯太', ruby: 'いのうえ そうた', nickname: 'いのちゃん', designatedCastIds: ['cast-11'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-18', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-14', name: '木村 勇人', ruby: 'きむら はやと', nickname: 'きむちゃん', designatedCastIds: ['cast-12'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-03', updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: 'きむちゃん用グラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-15', name: '林 智也', ruby: 'はやし ともや', nickname: 'はやちゃん', designatedCastIds: ['cast-13'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-27', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-16', name: '斎藤 洋介', ruby: 'さいとう ようすけ', nickname: 'さいちゃん', designatedCastIds: ['cast-14'], isAlert: true, alertReason: '酔った際に他の客とトラブルあり。要注意。', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-11-13', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-17', name: '清水 孝太', ruby: 'しみず こうた', nickname: 'しみちゃん', designatedCastIds: ['cast-15'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-15', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-18', name: '山崎 和也', ruby: 'やまざき かずや', nickname: 'やまざきちゃん', designatedCastIds: ['cast-16'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-05', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['山崎商事'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-19', name: '中島 聡', ruby: 'なかじま さとし', nickname: 'なかじまちゃん', designatedCastIds: ['cast-17'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-17', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-20', name: '森 修', ruby: 'もり おさむ', nickname: 'もりちゃん', designatedCastIds: ['cast-18'], isAlert: false, alertReason: '', memo: 'ビール専門。気さくな性格。', linkedCustomerIds: [], lastVisitDate: '2025-07-16', updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '森様マイグラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-21', name: '阿部 義弘', ruby: 'あべ よしひろ', nickname: 'あべちゃん', designatedCastIds: ['cast-19'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-01-27', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-22', name: '池田 哲也', ruby: 'いけだ てつや', nickname: 'いけちゃん', designatedCastIds: ['cast-20'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-11', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-23', name: '橋本 隆', ruby: 'はしもと たかし', nickname: 'はしちゃん', designatedCastIds: ['cast-21'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-01', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-24', name: '石川 博', ruby: 'いしかわ ひろし', nickname: 'いしちゃん', designatedCastIds: ['cast-22'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-02', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-25', name: '前田 正人', ruby: 'まえだ まさと', nickname: 'まえちゃん', designatedCastIds: ['cast-23'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-10-14', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-26', name: '岡田 信一', ruby: 'おかだ しんいち', nickname: 'おかちゃん', designatedCastIds: ['cast-24'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2024-07-31', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-27', name: '後藤 栄一', ruby: 'ごとう えいいち', nickname: 'ごとちゃん', designatedCastIds: ['cast-25'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-13', updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '後藤様専用', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-28', name: '長谷川 勝也', ruby: 'はせがわ かつや', nickname: 'はせちゃん', designatedCastIds: ['cast-26'], isAlert: false, alertReason: '', memo: '誕生日：7月4日。', linkedCustomerIds: [], lastVisitDate: '2026-02-21', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-29', name: '村上 俊介', ruby: 'むらかみ しゅんすけ', nickname: 'むらちゃん', designatedCastIds: ['cast-27'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-12-23', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-30', name: '近藤 裕二', ruby: 'こんどう ゆうじ', nickname: 'こんちゃん', designatedCastIds: ['cast-28'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-06-26', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-31', name: '坂本 秀樹', ruby: 'さかもと ひでき', nickname: 'さかちゃん', designatedCastIds: ['cast-29'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2024-03-23', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-32', name: '遠藤 達也', ruby: 'えんどう たつや', nickname: 'えんちゃん', designatedCastIds: ['cast-30'], isAlert: true, alertReason: 'クレーム常習。特定キャストへの過度な執着。', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-06', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-33', name: '青木 将太', ruby: 'あおき しょうた', nickname: 'あおちゃん', designatedCastIds: ['cast-31'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-17', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-34', name: '藤田 良平', ruby: 'ふじた りょうへい', nickname: 'ふじちゃん', designatedCastIds: ['cast-32'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-07', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-35', name: '西村 大樹', ruby: 'にしむら だいき', nickname: 'にしちゃん', designatedCastIds: ['cast-33'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-01', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-36', name: '福田 春樹', ruby: 'ふくだ はるき', nickname: 'ふくちゃん', designatedCastIds: ['cast-1'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-12-03', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-37', name: '岡本 剛', ruby: 'おかもと つよし', nickname: 'おかもとちゃん', designatedCastIds: ['cast-2'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2024-01-13', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-38', name: '三浦 航', ruby: 'みうら わたる', nickname: 'みうちゃん', designatedCastIds: ['cast-3'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-39', name: '松田 稔', ruby: 'まつだ みのる', nickname: 'まつだちゃん', designatedCastIds: ['cast-4'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-21', updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: 'マツダグラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-40', name: '中野 守', ruby: 'なかの まもる', nickname: 'なかのちゃん', designatedCastIds: ['cast-5'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-41', name: '原田 淳', ruby: 'はらだ じゅん', nickname: 'はらちゃん', designatedCastIds: ['cast-6'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-42', name: '小野 一成', ruby: 'おの かずなり', nickname: 'おのちゃん', designatedCastIds: ['cast-7'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-43', name: '竹内 幸雄', ruby: 'たけうち ゆきお', nickname: 'たけちゃん', designatedCastIds: ['cast-8'], isAlert: false, alertReason: '', memo: '日本酒好み。', linkedCustomerIds: [], lastVisitDate: '2026-03-19', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-44', name: '金子 進', ruby: 'かねこ すすむ', nickname: 'かねちゃん', designatedCastIds: ['cast-9'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-28', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-45', name: '藤本 豊', ruby: 'ふじもと ゆたか', nickname: 'ふじもとちゃん', designatedCastIds: ['cast-10'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-12', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-46', name: '丸山 仁', ruby: 'まるやま じん', nickname: 'まるちゃん', designatedCastIds: ['cast-11'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-08-15', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-47', name: '中川 克己', ruby: 'なかがわ かつみ', nickname: 'なかがわちゃん', designatedCastIds: ['cast-12'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-48', name: '宮崎 貞夫', ruby: 'みやざき さだお', nickname: 'みやちゃん', designatedCastIds: ['cast-13'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-49', name: '高橋 竜一', ruby: 'たかはし りゅういち', nickname: 'たかちゃん', designatedCastIds: ['cast-14'], isAlert: false, alertReason: '', memo: 'VIP常連。シャンパンタワー年2回。', linkedCustomerIds: [], lastVisitDate: '2026-03-22', updatedAt: '2026-03-23', isFavorite: true, hasGlass: true, glassMemo: '高橋VIPグラス', receiptNames: ['高橋グループ'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-50', name: '島田 英二', ruby: 'しまだ えいじ', nickname: 'しまちゃん', designatedCastIds: ['cast-15'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-22', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-51', name: '古川 浩二', ruby: 'ふるかわ こうじ', nickname: 'ふるちゃん', designatedCastIds: ['cast-16'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-24', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-52', name: '秋山 義雄', ruby: 'あきやま よしお', nickname: 'あきちゃん', designatedCastIds: ['cast-17'], isAlert: false, alertReason: '', memo: 'ハイボール専門。', linkedCustomerIds: [], lastVisitDate: '2025-11-23', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-53', name: '津田 正一', ruby: 'つだ しょういち', nickname: 'つだちゃん', designatedCastIds: ['cast-18'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-54', name: '下村 浩二', ruby: 'しもむら こうじ', nickname: 'しもちゃん', designatedCastIds: ['cast-19'], isAlert: false, alertReason: '', memo: '誕生日：12月24日。', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-55', name: '矢野 勉', ruby: 'やの つとむ', nickname: 'やのちゃん', designatedCastIds: ['cast-20'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-16', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-56', name: '本田 一男', ruby: 'ほんだ かずお', nickname: 'ほんちゃん', designatedCastIds: ['cast-21', 'cast-22'], isAlert: false, alertReason: '', memo: 'VIP。シャンパンタワー経験あり。', linkedCustomerIds: [], lastVisitDate: '2026-03-22', updatedAt: '2026-03-23', isFavorite: true, hasGlass: true, glassMemo: '本田プレミアム', receiptNames: ['本田ホールディングス'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-57', name: '浜田 和男', ruby: 'はまだ かずお', nickname: 'はまちゃん', designatedCastIds: ['cast-23'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-58', name: '西田 明宏', ruby: 'にしだ あきひろ', nickname: 'にしだちゃん', designatedCastIds: ['cast-24'], isAlert: true, alertReason: '深夜の大声クレーム歴あり。', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-12-18', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-59', name: '菊地 泰弘', ruby: 'きくち やすひろ', nickname: 'きくちゃん', designatedCastIds: ['cast-25'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-60', name: '大野 晋一', ruby: 'おおの しんいち', nickname: 'おおのちゃん', designatedCastIds: ['cast-26'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-14', updatedAt: '2026-03-23', isFavorite: true, hasGlass: true, glassMemo: '大野様マイグラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-61', name: '高野 一道', ruby: 'たかの かずみち', nickname: 'たかのちゃん', designatedCastIds: ['cast-27'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-09', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-62', name: '菅原 浩', ruby: 'すがわら ひろし', nickname: 'すがちゃん', designatedCastIds: ['cast-28'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-11-03', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-63', name: '笠原 真一', ruby: 'かさはら しんいち', nickname: 'かさちゃん', designatedCastIds: ['cast-29'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-64', name: '宮田 拓也', ruby: 'みやた たくや', nickname: 'みやたちゃん', designatedCastIds: ['cast-30'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-65', name: '杉山 翔太', ruby: 'すぎやま しょうた', nickname: 'すぎちゃん', designatedCastIds: ['cast-31'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-03', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-66', name: '増田 悠', ruby: 'ますだ はるか', nickname: 'ますちゃん', designatedCastIds: ['cast-32'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-67', name: '小川 蓮', ruby: 'おがわ れん', nickname: 'おがわちゃん', designatedCastIds: ['cast-33'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-68', name: '石井 律', ruby: 'いしい りつ', nickname: 'いしいちゃん', designatedCastIds: ['cast-1'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-17', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-69', name: '大塚 颯太', ruby: 'おおつか そうた', nickname: 'おおちゃん', designatedCastIds: ['cast-2'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-04', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-70', name: '岩田 勇人', ruby: 'いわた はやと', nickname: 'いわちゃん', designatedCastIds: ['cast-3'], isAlert: true, alertReason: '未払い歴1回。要確認。', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-12-28', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-71', name: '永田 智也', ruby: 'ながた ともや', nickname: 'ながちゃん', designatedCastIds: ['cast-4'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-05-17', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-72', name: '三田 洋介', ruby: 'みた ようすけ', nickname: 'みたちゃん', designatedCastIds: ['cast-5'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-73', name: '谷口 孝太', ruby: 'たにぐち こうた', nickname: 'たにちゃん', designatedCastIds: ['cast-6'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '谷口マイグラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-74', name: '安田 和也', ruby: 'やすだ かずや', nickname: 'やすちゃん', designatedCastIds: ['cast-7'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-75', name: '今村 聡', ruby: 'いまむら さとし', nickname: 'いまちゃん', designatedCastIds: ['cast-8'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-12', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-76', name: '川崎 修', ruby: 'かわさき おさむ', nickname: 'かわちゃん', designatedCastIds: ['cast-9'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-18', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-77', name: '野田 義弘', ruby: 'のだ よしひろ', nickname: 'のだちゃん', designatedCastIds: ['cast-10'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-78', name: '河野 哲也', ruby: 'こうの てつや', nickname: 'こうのちゃん', designatedCastIds: ['cast-11'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-79', name: '平野 隆', ruby: 'ひらの たかし', nickname: 'ひらちゃん', designatedCastIds: ['cast-12'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-80', name: '牧野 博', ruby: 'まきの ひろし', nickname: 'まきちゃん', designatedCastIds: ['cast-13'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-08', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-81', name: '関 正人', ruby: 'せき まさと', nickname: 'せきちゃん', designatedCastIds: ['cast-14'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-82', name: '中田 信一', ruby: 'なかた しんいち', nickname: 'なかたちゃん', designatedCastIds: ['cast-15'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-83', name: '内田 栄一', ruby: 'うちだ えいいち', nickname: 'うちちゃん', designatedCastIds: ['cast-16'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-16', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-84', name: '大西 勝也', ruby: 'おおにし かつや', nickname: 'おおにしちゃん', designatedCastIds: ['cast-17'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-24', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-85', name: '山内 俊介', ruby: 'やまうち しゅんすけ', nickname: 'やまうちちゃん', designatedCastIds: ['cast-18'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-86', name: '森田 裕二', ruby: 'もりた ゆうじ', nickname: 'もりたちゃん', designatedCastIds: ['cast-19'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2025-10-04', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-87', name: '星野 秀樹', ruby: 'ほしの ひでき', nickname: 'ほしちゃん', designatedCastIds: ['cast-20'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '星野グラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-88', name: '長野 達也', ruby: 'ながの たつや', nickname: 'ながのちゃん', designatedCastIds: ['cast-21'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-89', name: '柴田 将太', ruby: 'しばた しょうた', nickname: 'しばちゃん', designatedCastIds: ['cast-22'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-90', name: '藤原 良平', ruby: 'ふじわら りょうへい', nickname: 'ふじわらちゃん', designatedCastIds: ['cast-23'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-91', name: '村田 大樹', ruby: 'むらた だいき', nickname: 'むらたちゃん', designatedCastIds: ['cast-24'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-92', name: '沢田 春樹', ruby: 'さわだ はるき', nickname: 'さわちゃん', designatedCastIds: ['cast-25'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-93', name: '久保 剛', ruby: 'くぼ つよし', nickname: 'くぼちゃん', designatedCastIds: ['cast-26'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-10', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-94', name: '新井 航', ruby: 'あらい わたる', nickname: 'あらちゃん', designatedCastIds: ['cast-27'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-95', name: '千葉 稔', ruby: 'ちば みのる', nickname: 'ちばちゃん', designatedCastIds: ['cast-28'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-96', name: '上野 守', ruby: 'うえの まもる', nickname: 'うえちゃん', designatedCastIds: ['cast-29'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-97', name: '黒田 淳', ruby: 'くろだ じゅん', nickname: 'くろちゃん', designatedCastIds: ['cast-30'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-98', name: '高木 一成', ruby: 'たかぎ かずなり', nickname: 'たかぎちゃん', designatedCastIds: ['cast-31'], isAlert: true, alertReason: '過去に他客への絡み行為。注意要。', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-15', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-99', name: '横山 幸雄', ruby: 'よこやま ゆきお', nickname: 'よこちゃん', designatedCastIds: ['cast-32'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-100', name: '武田 進', ruby: 'たけだ すすむ', nickname: 'たけだちゃん', designatedCastIds: ['cast-33'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '武田グラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-101', name: '田村 豊', ruby: 'たむら ゆたか', nickname: 'たむちゃん', designatedCastIds: ['cast-1'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-102', name: '服部 仁', ruby: 'はっとり じん', nickname: 'はっちゃん', designatedCastIds: ['cast-2'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-103', name: '飯田 克己', ruby: 'いいだ かつみ', nickname: 'いいちゃん', designatedCastIds: ['cast-3'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-104', name: '大島 貞夫', ruby: 'おおしま さだお', nickname: 'おおしまちゃん', designatedCastIds: ['cast-4'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-105', name: '松尾 竜一', ruby: 'まつお りゅういち', nickname: 'まつおちゃん', designatedCastIds: ['cast-5'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-19', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-106', name: '飯塚 英二', ruby: 'いいづか えいじ', nickname: 'いいづかちゃん', designatedCastIds: ['cast-6'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-107', name: '辻 浩二', ruby: 'つじ こうじ', nickname: 'つじちゃん', designatedCastIds: ['cast-7'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-25', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-108', name: '富田 正一', ruby: 'とみた しょういち', nickname: 'とみちゃん', designatedCastIds: ['cast-8'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-109', name: '戸田 勉', ruby: 'とだ つとむ', nickname: 'とだちゃん', designatedCastIds: ['cast-9'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-110', name: '長沢 一男', ruby: 'ながさわ かずお', nickname: 'ながさわちゃん', designatedCastIds: ['cast-10'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-111', name: '野村 浩之', ruby: 'のむら ひろゆき', nickname: 'のむちゃん', designatedCastIds: ['cast-11'], isAlert: true, alertReason: '飲みすぎて迷惑行為の報告あり。', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-01-30', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-112', name: '寺田 政雄', ruby: 'てらだ まさお', nickname: 'てらちゃん', designatedCastIds: ['cast-12'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-113', name: '荒木 和男', ruby: 'あらき かずお', nickname: 'あらきちゃん', designatedCastIds: ['cast-13'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-114', name: '瀬川 明宏', ruby: 'せがわ あきひろ', nickname: 'せがちゃん', designatedCastIds: ['cast-14'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: true, glassMemo: '瀬川プレミアム', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-115', name: '水野 泰弘', ruby: 'みずの やすひろ', nickname: 'みずちゃん', designatedCastIds: ['cast-15'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-21', updatedAt: '2026-03-23', isFavorite: true, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-116', name: '竹田 晋一', ruby: 'たけた しんいち', nickname: 'たけたちゃん', designatedCastIds: ['cast-16'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-06', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-117', name: '坂田 一道', ruby: 'さかた かずみち', nickname: 'さかたちゃん', designatedCastIds: ['cast-17'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-118', name: '吉川 浩', ruby: 'よしかわ ひろし', nickname: 'よしかわちゃん', designatedCastIds: ['cast-18'], isAlert: false, alertReason: '', memo: '誕生日：9月1日。', linkedCustomerIds: [], lastVisitDate: null, updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-119', name: '和田 真一', ruby: 'わだ しんいち', nickname: 'わだちゃん', designatedCastIds: ['cast-19'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-03-20', updatedAt: '2026-03-23', isFavorite: true, hasGlass: true, glassMemo: '和田様グラス', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-120', name: '渡部 拓海', ruby: 'わたべ たくみ', nickname: 'わたべちゃん', designatedCastIds: ['cast-20'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: '2026-02-11', updatedAt: '2026-03-23', isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
]

export const mockBottles: Bottle[] = [
  {
    id: 'bottle-1',
    customerId: 'customer-1',
    name: 'ドンペリニヨン 2015',
    remaining: '100%',
    openedDate: '2026-03-16',
  },
  {
    id: 'bottle-2',
    customerId: 'customer-1',
    name: 'バランタイン 17年',
    remaining: '50%',
    openedDate: '2026-02-21',
  },
  {
    id: 'bottle-3',
    customerId: 'customer-1',
    name: 'ヘネシー XO',
    remaining: '10%',
    openedDate: '2025-12-23',
  },
  {
    id: 'bottle-4',
    customerId: 'customer-2',
    name: 'シーバスリーガル 18年',
    remaining: '75%',
    openedDate: '2026-02-21',
  },
  {
    id: 'bottle-5',
    customerId: 'customer-4',
    name: 'サントリー響 21年',
    remaining: '30%',
    openedDate: '2026-02-06',
  },
  {
    id: 'bottle-6',
    customerId: 'customer-5',
    name: 'ジョニーウォーカー ブルーラベル',
    remaining: '100%',
    openedDate: '2026-01-22',
  },
  {
    id: 'bottle-7',
    customerId: 'customer-6',
    name: 'モエ・エ・シャンドン',
    remaining: '100%',
    openedDate: '2026-03-20',
  },
  {
    id: 'bottle-8',
    customerId: 'customer-7',
    name: '山崎 12年',
    remaining: '60%',
    openedDate: '2026-03-18',
  },
  {
    id: 'bottle-9',
    customerId: 'customer-8',
    name: 'マッカラン 18年',
    remaining: '80%',
    openedDate: '2026-03-13',
  },
  {
    id: 'bottle-10',
    customerId: 'customer-10',
    name: '獺祭 二割三分',
    remaining: '50%',
    openedDate: '2026-03-03',
  },
  {
    id: 'bottle-11',
    customerId: 'customer-12',
    name: 'レミーマルタン XO',
    remaining: '70%',
    openedDate: '2026-03-15',
  },
  {
    id: 'bottle-12',
    customerId: 'customer-15',
    name: 'ペトリュス 2018',
    remaining: '100%',
    openedDate: '2026-03-08',
  },
  {
    id: 'bottle-13',
    customerId: 'customer-16',
    name: 'ベルヴェデール ウォッカ',
    remaining: '40%',
    openedDate: '2026-03-21',
  },
  {
    id: 'bottle-14',
    customerId: 'customer-18',
    name: 'グレンリベット 18年',
    remaining: '25%',
    openedDate: '2026-02-26',
  },
  {
    id: 'bottle-15',
    customerId: 'customer-19',
    name: 'クリュッグ グランド キュヴェ',
    remaining: '100%',
    openedDate: '2026-03-17',
  },
  {
    id: 'bottle-16',
    customerId: 'customer-22',
    name: 'アードベッグ 10年',
    remaining: '85%',
    openedDate: '2026-03-22',
  },
  { id: 'bottle-17', customerId: 'customer-27', name: '竹鶴 17年', remaining: '70%', openedDate: '2026-03-19' },
  { id: 'bottle-18', customerId: 'customer-29', name: 'シャトー・マルゴー 2017', remaining: '50%', openedDate: '2026-03-16' },
  { id: 'bottle-19', customerId: 'customer-29', name: 'オーパスワン 2019', remaining: '100%', openedDate: '2026-03-21' },
  { id: 'bottle-20', customerId: 'customer-32', name: 'ボウモア 15年', remaining: '40%', openedDate: '2026-03-11' },
  { id: 'bottle-21', customerId: 'customer-34', name: 'ワイルドターキー 12年', remaining: '60%', openedDate: '2026-03-15' },
  { id: 'bottle-22', customerId: 'customer-35', name: 'グレンフィディック 18年', remaining: '90%', openedDate: '2026-03-18' },
  { id: 'bottle-23', customerId: 'customer-36', name: 'ローラン・ペリエ ロゼ', remaining: '100%', openedDate: '2026-03-10' },
  { id: 'bottle-24', customerId: 'customer-37', name: 'ドンペリニヨン ロゼ 2013', remaining: '100%', openedDate: '2026-03-21' },
  { id: 'bottle-25', customerId: 'customer-37', name: '山崎 18年', remaining: '35%', openedDate: '2026-02-21' },
  { id: 'bottle-26', customerId: 'customer-42', name: 'ラフロイグ 10年', remaining: '65%', openedDate: '2026-03-14' },
  { id: 'bottle-27', customerId: 'customer-44', name: 'タリスカー 10年', remaining: '80%', openedDate: '2026-03-04' },
  { id: 'bottle-28', customerId: 'customer-45', name: 'グレンモーレンジ 18年', remaining: '55%', openedDate: '2026-02-18' },
  { id: 'bottle-29', customerId: 'customer-47', name: 'シーバスリーガル 25年', remaining: '45%', openedDate: '2026-03-03' },
  { id: 'bottle-30', customerId: 'customer-50', name: 'バランタイン 21年', remaining: '75%', openedDate: '2026-03-11' },
  { id: 'bottle-31', customerId: 'customer-52', name: 'グレンリベット 25年', remaining: '90%', openedDate: '2026-02-14' },
  { id: 'bottle-32', customerId: 'customer-56', name: 'カナディアンクラブ 20年', remaining: '60%', openedDate: '2026-03-09' },
  { id: 'bottle-33', customerId: 'customer-58', name: 'サントリー白州 12年', remaining: '30%', openedDate: '2026-02-11' },
  { id: 'bottle-34', customerId: 'customer-60', name: 'ロン・サカパ 23年', remaining: '85%', openedDate: '2026-03-19' },
  { id: 'bottle-35', customerId: 'customer-63', name: 'ペリエジュエ ベル エポック', remaining: '100%', openedDate: '2026-03-16' },
  { id: 'bottle-36', customerId: 'customer-67', name: 'レミーマルタン ルイ13世', remaining: '20%', openedDate: '2026-01-22' },
  { id: 'bottle-37', customerId: 'customer-70', name: 'クリスタル 2015', remaining: '100%', openedDate: '2026-03-22' },
  { id: 'bottle-38', customerId: 'customer-70', name: 'アルマンド ブリニャック', remaining: '50%', openedDate: '2026-03-08' },
  { id: 'bottle-39', customerId: 'customer-71', name: '響 JAPANESE HARMONY', remaining: '70%', openedDate: '2026-03-15' },
  { id: 'bottle-40', customerId: 'customer-76', name: '余市 10年', remaining: '45%', openedDate: '2026-02-24' },
  { id: 'bottle-41', customerId: 'customer-78', name: 'シャトー・ラフィット 2016', remaining: '100%', openedDate: '2026-03-17' },
  { id: 'bottle-42', customerId: 'customer-80', name: 'バランタイン 30年', remaining: '55%', openedDate: '2026-02-26' },
  { id: 'bottle-43', customerId: 'customer-87', name: '伊佐美', remaining: '80%', openedDate: '2026-03-18' },
  { id: 'bottle-44', customerId: 'customer-88', name: '黒龍 特吟', remaining: '65%', openedDate: '2026-02-07' },
  { id: 'bottle-45', customerId: 'customer-90', name: 'モエ・エ・シャンドン ネクター', remaining: '100%', openedDate: '2026-02-25' },
  { id: 'bottle-46', customerId: 'customer-94', name: 'ドンペリニヨン 2012', remaining: '30%', openedDate: '2026-02-01' },
  { id: 'bottle-47', customerId: 'customer-94', name: 'アルマンド ゴールド', remaining: '100%', openedDate: '2026-03-20' },
  { id: 'bottle-48', customerId: 'customer-100', name: 'クリスタル ロゼ 2014', remaining: '100%', openedDate: '2026-03-22' },
  { id: 'bottle-49', customerId: 'customer-100', name: 'ルイ・ロデレール ブリュット', remaining: '60%', openedDate: '2026-03-03' },
]

export const mockVisitRecords: VisitRecord[] = [
  {
    id: 'visit-1',
    customerId: 'customer-1',
    visitDate: '2026-03-16',
    designatedCastIds: ['cast-1'],
    inStoreCastIds: ['cast-2'],
    bottlesOpened: ['bottle-1'],
    bottlesUsed: ['bottle-2'],
    memo: 'ドンペリ開封。大変ご機嫌でした。',
  },
  {
    id: 'visit-2',
    customerId: 'customer-1',
    visitDate: '2026-02-21',
    designatedCastIds: ['cast-1'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-2'],
    bottlesUsed: ['bottle-3'],
    memo: 'バランタイン開封。',
  },
  {
    id: 'visit-3',
    customerId: 'customer-2',
    visitDate: '2026-02-21',
    designatedCastIds: ['cast-2'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-4'],
    bottlesUsed: [],
    memo: '',
  },
  {
    id: 'visit-4',
    customerId: 'customer-4',
    visitDate: '2026-03-09',
    designatedCastIds: ['cast-1'],
    inStoreCastIds: ['cast-3'],
    bottlesOpened: [],
    bottlesUsed: ['bottle-5'],
    memo: '響を使用。',
  },
  {
    id: 'visit-5',
    customerId: 'customer-5',
    visitDate: '2026-01-22',
    designatedCastIds: ['cast-3'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-6'],
    bottlesUsed: [],
    memo: 'ブルーラベル開封。誕生日のお祝い。',
  },
  {
    id: 'visit-6',
    customerId: 'customer-6',
    visitDate: '2026-03-20',
    designatedCastIds: ['cast-2'],
    inStoreCastIds: ['cast-1'],
    bottlesOpened: ['bottle-7'],
    bottlesUsed: [],
    memo: '接待利用。領収書発行済。',
  },
  {
    id: 'visit-7',
    customerId: 'customer-7',
    visitDate: '2026-03-18',
    designatedCastIds: ['cast-4'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-8'],
    bottlesUsed: [],
    memo: '山崎開封。',
  },
  {
    id: 'visit-8',
    customerId: 'customer-8',
    visitDate: '2026-03-13',
    designatedCastIds: ['cast-5'],
    inStoreCastIds: ['cast-6'],
    bottlesOpened: ['bottle-9'],
    bottlesUsed: [],
    memo: '小林様・加藤様ご一緒に来店。',
  },
  {
    id: 'visit-9',
    customerId: 'customer-10',
    visitDate: '2026-03-03',
    designatedCastIds: ['cast-6'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-10'],
    bottlesUsed: [],
    memo: '獺祭開封。日本酒の話で盛り上がり。',
  },
  {
    id: 'visit-10',
    customerId: 'customer-12',
    visitDate: '2026-03-15',
    designatedCastIds: ['cast-3', 'cast-8'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-11'],
    bottlesUsed: [],
    memo: 'XO開封。',
  },
  {
    id: 'visit-11',
    customerId: 'customer-16',
    visitDate: '2026-03-21',
    designatedCastIds: ['cast-12'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-13'],
    bottlesUsed: [],
    memo: '早めにお帰り。',
  },
  {
    id: 'visit-12',
    customerId: 'customer-22',
    visitDate: '2026-03-22',
    designatedCastIds: ['cast-17'],
    inStoreCastIds: ['cast-18'],
    bottlesOpened: ['bottle-16'],
    bottlesUsed: [],
    memo: '毎週来店。今週も楽しんでいただいた。',
  },
  { id: 'visit-13', customerId: 'customer-27', visitDate: '2026-03-19', designatedCastIds: ['cast-24'], inStoreCastIds: ['cast-25'], bottlesOpened: ['bottle-17'], bottlesUsed: [], memo: '竹鶴開封。ジャズの話で盛り上がり。' },
  { id: 'visit-14', customerId: 'customer-29', visitDate: '2026-03-16', designatedCastIds: ['cast-26'], inStoreCastIds: ['cast-27'], bottlesOpened: ['bottle-18'], bottlesUsed: [], memo: 'マルゴー開封。' },
  { id: 'visit-15', customerId: 'customer-29', visitDate: '2026-03-21', designatedCastIds: ['cast-26'], inStoreCastIds: [], bottlesOpened: ['bottle-19'], bottlesUsed: ['bottle-18'], memo: 'オーパスワン開封。' },
  { id: 'visit-16', customerId: 'customer-32', visitDate: '2026-03-11', designatedCastIds: ['cast-29'], inStoreCastIds: ['cast-30'], bottlesOpened: ['bottle-20'], bottlesUsed: [], memo: '' },
  { id: 'visit-17', customerId: 'customer-32', visitDate: '2026-03-20', designatedCastIds: ['cast-29'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-20'], memo: '残量少なめ。' },
  { id: 'visit-18', customerId: 'customer-34', visitDate: '2026-03-15', designatedCastIds: ['cast-31'], inStoreCastIds: ['cast-32'], bottlesOpened: ['bottle-21'], bottlesUsed: [], memo: 'ターキー開封。' },
  { id: 'visit-19', customerId: 'customer-35', visitDate: '2026-03-18', designatedCastIds: ['cast-32'], inStoreCastIds: ['cast-33'], bottlesOpened: ['bottle-22'], bottlesUsed: [], memo: 'グレンフィディック開封。' },
  { id: 'visit-20', customerId: 'customer-37', visitDate: '2026-02-21', designatedCastIds: ['cast-1'], inStoreCastIds: ['cast-24', 'cast-25'], bottlesOpened: ['bottle-25'], bottlesUsed: [], memo: '山崎開封。大人数での来店。' },
  { id: 'visit-21', customerId: 'customer-37', visitDate: '2026-03-21', designatedCastIds: ['cast-1', 'cast-24'], inStoreCastIds: ['cast-26'], bottlesOpened: ['bottle-24'], bottlesUsed: ['bottle-25'], memo: 'ドンペリロゼ開封。接待利用。' },
  { id: 'visit-22', customerId: 'customer-42', visitDate: '2026-03-14', designatedCastIds: ['cast-6'], inStoreCastIds: ['cast-7'], bottlesOpened: ['bottle-26'], bottlesUsed: [], memo: 'ラフロイグ開封。' },
  { id: 'visit-23', customerId: 'customer-44', visitDate: '2026-03-04', designatedCastIds: ['cast-8'], inStoreCastIds: [], bottlesOpened: ['bottle-27'], bottlesUsed: [], memo: '' },
  { id: 'visit-24', customerId: 'customer-47', visitDate: '2026-03-03', designatedCastIds: ['cast-11'], inStoreCastIds: ['cast-12'], bottlesOpened: ['bottle-29'], bottlesUsed: [], memo: 'シーバス25年開封。' },
  { id: 'visit-25', customerId: 'customer-47', visitDate: '2026-03-17', designatedCastIds: ['cast-11'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-29'], memo: '' },
  { id: 'visit-26', customerId: 'customer-50', visitDate: '2026-03-11', designatedCastIds: ['cast-14'], inStoreCastIds: ['cast-15'], bottlesOpened: ['bottle-30'], bottlesUsed: [], memo: '接待利用。領収書発行。' },
  { id: 'visit-27', customerId: 'customer-56', visitDate: '2026-03-09', designatedCastIds: ['cast-20'], inStoreCastIds: ['cast-21'], bottlesOpened: ['bottle-32'], bottlesUsed: [], memo: '' },
  { id: 'visit-28', customerId: 'customer-58', visitDate: '2026-02-11', designatedCastIds: ['cast-22'], inStoreCastIds: [], bottlesOpened: ['bottle-33'], bottlesUsed: [], memo: '白州開封。水割りで飲む。' },
  { id: 'visit-29', customerId: 'customer-58', visitDate: '2026-03-13', designatedCastIds: ['cast-22'], inStoreCastIds: ['cast-23'], bottlesOpened: [], bottlesUsed: ['bottle-33'], memo: '' },
  { id: 'visit-30', customerId: 'customer-60', visitDate: '2026-03-19', designatedCastIds: ['cast-24'], inStoreCastIds: ['cast-25', 'cast-26'], bottlesOpened: ['bottle-34'], bottlesUsed: [], memo: 'サカパ開封。' },
  { id: 'visit-31', customerId: 'customer-63', visitDate: '2026-03-16', designatedCastIds: ['cast-27'], inStoreCastIds: [], bottlesOpened: ['bottle-35'], bottlesUsed: [], memo: '' },
  { id: 'visit-32', customerId: 'customer-67', visitDate: '2026-01-22', designatedCastIds: ['cast-31'], inStoreCastIds: ['cast-32'], bottlesOpened: ['bottle-36'], bottlesUsed: [], memo: 'ルイ13世開封。記念の来店。' },
  { id: 'visit-33', customerId: 'customer-67', visitDate: '2026-03-12', designatedCastIds: ['cast-31'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-36'], memo: 'ワイングラスで飲んでいただいた。' },
  { id: 'visit-34', customerId: 'customer-70', visitDate: '2026-03-08', designatedCastIds: ['cast-1'], inStoreCastIds: ['cast-26', 'cast-27'], bottlesOpened: ['bottle-38'], bottlesUsed: [], memo: 'アルマンド開封。大型接待。' },
  { id: 'visit-35', customerId: 'customer-70', visitDate: '2026-03-22', designatedCastIds: ['cast-1', 'cast-26'], inStoreCastIds: ['cast-28'], bottlesOpened: ['bottle-37'], bottlesUsed: ['bottle-38'], memo: 'クリスタル開封。' },
  { id: 'visit-36', customerId: 'customer-71', visitDate: '2026-03-15', designatedCastIds: ['cast-2', 'cast-25'], inStoreCastIds: ['cast-3'], bottlesOpened: ['bottle-39'], bottlesUsed: [], memo: '響開封。' },
  { id: 'visit-37', customerId: 'customer-76', visitDate: '2026-02-24', designatedCastIds: ['cast-7'], inStoreCastIds: ['cast-8'], bottlesOpened: ['bottle-40'], bottlesUsed: [], memo: '余市開封。' },
  { id: 'visit-38', customerId: 'customer-78', visitDate: '2026-03-17', designatedCastIds: ['cast-9'], inStoreCastIds: ['cast-10', 'cast-11'], bottlesOpened: ['bottle-41'], bottlesUsed: [], memo: 'ラフィット開封。ワインの話で盛り上がり。' },
  { id: 'visit-39', customerId: 'customer-80', visitDate: '2026-02-26', designatedCastIds: ['cast-11'], inStoreCastIds: ['cast-12', 'cast-13'], bottlesOpened: ['bottle-42'], bottlesUsed: [], memo: 'バランタイン30年開封。接待利用。' },
  { id: 'visit-40', customerId: 'customer-80', visitDate: '2026-03-10', designatedCastIds: ['cast-11'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-42'], memo: '' },
  { id: 'visit-41', customerId: 'customer-87', visitDate: '2026-03-18', designatedCastIds: ['cast-18'], inStoreCastIds: ['cast-19'], bottlesOpened: ['bottle-43'], bottlesUsed: [], memo: '伊佐美開封。焼酎好きのお客様。' },
  { id: 'visit-42', customerId: 'customer-88', visitDate: '2026-02-07', designatedCastIds: ['cast-19'], inStoreCastIds: [], bottlesOpened: ['bottle-44'], bottlesUsed: [], memo: '黒龍開封。日本酒の話で盛り上がり。' },
  { id: 'visit-43', customerId: 'customer-90', visitDate: '2026-02-25', designatedCastIds: ['cast-21'], inStoreCastIds: ['cast-22'], bottlesOpened: ['bottle-45'], bottlesUsed: [], memo: 'モエネクター開封。' },
  { id: 'visit-44', customerId: 'customer-94', visitDate: '2026-02-01', designatedCastIds: ['cast-25'], inStoreCastIds: ['cast-26', 'cast-27'], bottlesOpened: ['bottle-46'], bottlesUsed: [], memo: 'ドンペリ開封。週1常連様。' },
  { id: 'visit-45', customerId: 'customer-94', visitDate: '2026-03-20', designatedCastIds: ['cast-25'], inStoreCastIds: ['cast-28'], bottlesOpened: ['bottle-47'], bottlesUsed: ['bottle-46'], memo: 'アルマンドゴールド開封。今週も楽しんでいただいた。' },
  { id: 'visit-46', customerId: 'customer-100', visitDate: '2026-03-03', designatedCastIds: ['cast-31'], inStoreCastIds: ['cast-32', 'cast-33'], bottlesOpened: ['bottle-49'], bottlesUsed: [], memo: 'ブリュット開封。大人数来店。' },
  { id: 'visit-47', customerId: 'customer-100', visitDate: '2026-03-22', designatedCastIds: ['cast-31', 'cast-32'], inStoreCastIds: ['cast-24', 'cast-25'], bottlesOpened: ['bottle-48'], bottlesUsed: ['bottle-49'], memo: 'クリスタルロゼ開封。シャンパンタワー実施。大盛況。' },
]

// ─── Dummy Reservations (3 months: Feb–Apr 2026, no Sundays/holidays) ─────────

const _castIds = ['cast-1','cast-2','cast-3','cast-4','cast-5','cast-6','cast-7','cast-8','cast-9','cast-10','cast-11','cast-12','cast-13','cast-14','cast-15','cast-16','cast-17','cast-18','cast-19','cast-20']
const _times = ['19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30']
const _sizes = [2,2,1,3,2,2,1,4,2,2]
const _guests = ['田中','鈴木','佐藤','高橋','伊藤','渡辺','山本','中村','小林','加藤','松本','井上','木村','林','斎藤']

function _r(
  id: number, date: string, tIdx: number,
  opts?: { partyPlan?: boolean; accompanied?: boolean }
): Reservation {
  const i = id - 1
  const isNew = i % 4 === 3
  const isDesig = i % 3 === 0
  const isAccomp = opts?.accompanied ?? (i % 9 === 2)
  const isPP = opts?.partyPlan ?? false
  return {
    id: `res-${id}`,
    date,
    time: _times[tIdx % _times.length],
    partySize: _sizes[i % _sizes.length],
    hasDesignation: isDesig,
    designatedCastIds: isDesig ? [_castIds[i % _castIds.length]] : [],
    isAccompanied: isAccomp,
    accompaniedCastIds: isAccomp ? [_castIds[(i + 5) % _castIds.length]] : [],
    customerType: isNew ? 'new' : 'existing',
    customerIds: isNew ? [] : [`customer-${(i % 30) + 1}`],
    guestName: isNew ? _guests[i % _guests.length] : '',
    phone: '',
    isVisited: false,
    priceType: isPP ? 'party' : 'normal',
    partyPlanPrice: isPP ? [30000,25000,40000,35000][i % 4] : null,
    partyPlanMinutes: isPP ? [90,120,90,120][i % 4] : null,
    memo: '',
    updatedAt: `${date}T12:00:00.000Z`,
    updatedBy: 'test',
  }
}

export const mockReservations: Reservation[] = [
  // ── February 2026 ──
  _r(1,'2026-02-02',0), _r(2,'2026-02-03',2), _r(3,'2026-02-04',1), _r(4,'2026-02-05',3),
  _r(5,'2026-02-06',0), _r(6,'2026-02-06',4), _r(7,'2026-02-06',7,{partyPlan:true}),
  _r(8,'2026-02-07',1), _r(9,'2026-02-07',5), _r(10,'2026-02-07',3,{partyPlan:true}),
  _r(11,'2026-02-09',2), _r(12,'2026-02-10',0),
  _r(13,'2026-02-12',4),
  _r(14,'2026-02-13',0), _r(15,'2026-02-13',2), _r(16,'2026-02-13',6,{partyPlan:true}),
  _r(17,'2026-02-14',1), _r(18,'2026-02-14',4), _r(19,'2026-02-14',7,{partyPlan:true}),
  _r(20,'2026-02-16',0), _r(21,'2026-02-17',2), _r(22,'2026-02-18',1), _r(23,'2026-02-19',3),
  _r(24,'2026-02-20',0), _r(25,'2026-02-20',4), _r(26,'2026-02-20',8),
  _r(27,'2026-02-21',2), _r(28,'2026-02-21',5), _r(29,'2026-02-21',7,{partyPlan:true}),
  _r(30,'2026-02-24',1), _r(31,'2026-02-25',3), _r(32,'2026-02-26',0),
  _r(33,'2026-02-27',0), _r(34,'2026-02-27',4), _r(35,'2026-02-27',7),
  _r(36,'2026-02-28',1), _r(37,'2026-02-28',5), _r(38,'2026-02-28',8,{partyPlan:true}),
  // ── March 2026 ──
  _r(39,'2026-03-02',2), _r(40,'2026-03-03',0), _r(41,'2026-03-04',3), _r(42,'2026-03-05',1),
  _r(43,'2026-03-06',0), _r(44,'2026-03-06',4), _r(45,'2026-03-06',7,{partyPlan:true}),
  _r(46,'2026-03-07',1), _r(47,'2026-03-07',5), _r(48,'2026-03-07',8,{partyPlan:true}),
  _r(49,'2026-03-09',2), _r(50,'2026-03-10',0), _r(51,'2026-03-11',3), _r(52,'2026-03-12',1),
  _r(53,'2026-03-13',0), _r(54,'2026-03-13',4), _r(55,'2026-03-13',7),
  _r(56,'2026-03-14',2), _r(57,'2026-03-14',5), _r(58,'2026-03-14',8,{partyPlan:true}),
  _r(59,'2026-03-16',0), _r(60,'2026-03-17',2), _r(61,'2026-03-18',4), _r(62,'2026-03-19',1),
  _r(63,'2026-03-21',0), _r(64,'2026-03-21',4), _r(65,'2026-03-21',7,{partyPlan:true}),
  _r(66,'2026-03-23',2), _r(67,'2026-03-24',0), _r(68,'2026-03-25',3), _r(69,'2026-03-26',1),
  _r(70,'2026-03-27',0), _r(71,'2026-03-27',4), _r(72,'2026-03-27',7),
  _r(73,'2026-03-28',2), _r(74,'2026-03-28',5), _r(75,'2026-03-28',9,{partyPlan:true}),
  _r(76,'2026-03-30',0), _r(77,'2026-03-30',4), _r(78,'2026-03-31',2),
  // ── April 2026 ──
  _r(79,'2026-04-01',0), _r(80,'2026-04-02',2), _r(81,'2026-04-02',5),
  _r(82,'2026-04-03',0), _r(83,'2026-04-03',4), _r(84,'2026-04-03',8,{partyPlan:true}),
  _r(85,'2026-04-04',2), _r(86,'2026-04-04',5), _r(87,'2026-04-04',8,{partyPlan:true}),
  _r(88,'2026-04-06',1), _r(89,'2026-04-07',3), _r(90,'2026-04-08',0), _r(91,'2026-04-09',2),
  _r(92,'2026-04-10',0), _r(93,'2026-04-10',4), _r(94,'2026-04-10',7,{partyPlan:true}),
  _r(95,'2026-04-11',1), _r(96,'2026-04-11',5), _r(97,'2026-04-11',8,{partyPlan:true}),
  _r(98,'2026-04-13',2), _r(99,'2026-04-14',0), _r(100,'2026-04-15',3), _r(101,'2026-04-16',1),
  _r(102,'2026-04-17',0), _r(103,'2026-04-17',4), _r(104,'2026-04-17',7),
  _r(105,'2026-04-18',2), _r(106,'2026-04-18',5), _r(107,'2026-04-18',9,{partyPlan:true}),
  _r(108,'2026-04-20',0), _r(109,'2026-04-21',2), _r(110,'2026-04-22',4), _r(111,'2026-04-23',1),
  _r(112,'2026-04-24',0), _r(113,'2026-04-24',4), _r(114,'2026-04-24',7),
  _r(115,'2026-04-25',2), _r(116,'2026-04-25',5), _r(117,'2026-04-25',8,{partyPlan:true}),
  _r(118,'2026-04-27',0), _r(119,'2026-04-28',2), _r(120,'2026-04-30',4),
]
