import type { Customer, Bottle, Cast, VisitRecord, Reservation } from '@/types'

export const mockCasts: Cast[] = [
  { id: 'cast-1', name: '桜', ruby: 'さくら', memo: 'ナンバーワン。シャンパン担当。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-2', name: '愛', ruby: 'あい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-3', name: '蘭', ruby: 'らん', memo: '土日のみ出勤。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-4', name: '葵', ruby: 'あおい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-5', name: '凛', ruby: 'りん', memo: '新人。フォロー必要。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-6', name: '麻衣', ruby: 'まい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-7', name: '瑠璃', ruby: 'るり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-8', name: '奈々', ruby: 'なな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-9', name: '彩花', ruby: 'あやか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-10', name: '雪', ruby: 'ゆき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-11', name: '茉莉', ruby: 'まり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-12', name: '優香', ruby: 'ゆか', memo: '平日のみ。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-13', name: '心春', ruby: 'こはる', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-14', name: '結衣', ruby: 'ゆい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-15', name: '真琴', ruby: 'まこと', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-16', name: '里菜', ruby: 'りな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-17', name: '詩織', ruby: 'しおり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-18', name: '華', ruby: 'はな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-19', name: '千夏', ruby: 'ちなつ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-20', name: '明日香', ruby: 'あすか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-21', name: '紬', ruby: 'つむぎ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-22', name: '柚希', ruby: 'ゆずき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-23', name: '朱里', ruby: 'あかり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-24', name: '美咲', ruby: 'みさき', memo: '週3出勤。人気急上昇中。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-25', name: '七海', ruby: 'ななみ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-26', name: '恵', ruby: 'めぐみ', memo: 'ベテラン。接客経験10年以上。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-27', name: '沙織', ruby: 'さおり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-28', name: '理沙', ruby: 'りさ', memo: '土日祝のみ出勤。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-29', name: '夏希', ruby: 'なつき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-30', name: '芽衣', ruby: 'めい', memo: '新人。丁寧な接客が好評。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-31', name: '千尋', ruby: 'ちひろ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-32', name: '由美', ruby: 'ゆみ', memo: 'ナンバー候補。歌が得意。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-33', name: '萌', ruby: 'もえ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-34', name: '陽菜', ruby: 'ひな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-35', name: '花音', ruby: 'かのん', memo: '歌唱力が高い。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-36', name: '珠希', ruby: 'たまき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-37', name: '琴葉', ruby: 'ことは', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-38', name: '紗良', ruby: 'さら', memo: '週4出勤。接客安定。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-39', name: '初音', ruby: 'はつね', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-40', name: '彩乃', ruby: 'あやの', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-41', name: '澪', ruby: 'みお', memo: '落ち着いた雰囲気が人気。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-42', name: '鈴', ruby: 'すず', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-43', name: '望', ruby: 'のぞみ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-44', name: '穂香', ruby: 'ほのか', memo: '新人。元気が売り。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-45', name: '杏', ruby: 'あんず', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-46', name: '和香', ruby: 'わか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-47', name: '小春', ruby: 'こはる', memo: '土日のみ。学生。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-48', name: '光', ruby: 'ひかり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-49', name: '桃花', ruby: 'ももか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-50', name: '柊', ruby: 'ひいらぎ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-51', name: '藍', ruby: 'あい', memo: '落ち着いた接客スタイル。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-52', name: '茜', ruby: 'あかね', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-53', name: '涼', ruby: 'りょう', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-54', name: '美羽', ruby: 'みう', memo: '週3。ダンスが得意。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-55', name: '月', ruby: 'つき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-56', name: '星奈', ruby: 'せいな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-57', name: '柚子', ruby: 'ゆず', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-58', name: '夕佳', ruby: 'ゆか', memo: 'ベテラン組。頼れるキャスト。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-59', name: '宙', ruby: 'そら', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-60', name: '玲', ruby: 'れい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-61', name: '彩', ruby: 'いろは', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-62', name: '美桜', ruby: 'みお', memo: '新人。研修中。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-63', name: '音羽', ruby: 'おとは', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-64', name: '紅葉', ruby: 'もみじ', memo: '秋からの新メンバー。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-65', name: '春菜', ruby: 'はるな', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-66', name: '白雪', ruby: 'しらゆき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-67', name: '夕凪', ruby: 'ゆうなぎ', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-68', name: '綺羅', ruby: 'きら', memo: 'ステージパフォーマンスが好評。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-69', name: '汐里', ruby: 'しおり', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-70', name: '水月', ruby: 'みつき', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-71', name: '優', ruby: 'ゆう', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-72', name: '詩', ruby: 'うた', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-73', name: '菜緒', ruby: 'なお', memo: '平日限定出勤。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-74', name: '舞', ruby: 'まい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-75', name: '胡蝶', ruby: 'こちょう', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-76', name: '真白', ruby: 'ましろ', memo: '週2。副業キャスト。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-77', name: '一花', ruby: 'いちか', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-78', name: '珊瑚', ruby: 'さんご', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-79', name: '暖', ruby: 'はる', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-80', name: '颯', ruby: 'そう', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-81', name: '蒼', ruby: 'あお', memo: 'クールな雰囲気が人気。', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-82', name: '紫苑', ruby: 'しおん', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
  { id: 'cast-83', name: '流星', ruby: 'りゅうせい', memo: '', updatedAt: new Date().toISOString(), updatedBy: '' },
]

export const mockCustomers: Customer[] = [
  {
    id: 'customer-1',
    name: '田中 一郎',
    ruby: 'たなか いちろう',
    nickname: 'たなちゃん',
    designatedCastIds: ['cast-1'],
    isAlert: false,
    alertReason: '',
    memo: 'VIPクライアント。高級シャンパン好み。',
    linkedCustomerIds: ['customer-4'],
    lastVisitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-2',
    name: '鈴木 健太',
    ruby: 'すずき けんた',
    nickname: 'すーさん',
    designatedCastIds: ['cast-2'],
    isAlert: true,
    alertReason: '支払いトラブルあり。過去に無断キャンセル2回。',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-3',
    name: '佐藤 大輔',
    ruby: 'さとう だいすけ',
    nickname: 'だいちゃん',
    designatedCastIds: [],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-4',
    name: '山田 誠',
    ruby: 'やまだ まこと',
    nickname: 'やまちゃん',
    designatedCastIds: ['cast-1', 'cast-2'],
    isAlert: false,
    alertReason: '',
    memo: 'ウィスキー好み。田中様の紹介。',
    linkedCustomerIds: ['customer-1'],
    lastVisitDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-5',
    name: '伊藤 博',
    ruby: 'いとう ひろし',
    nickname: 'ひろさん',
    designatedCastIds: ['cast-3'],
    isAlert: false,
    alertReason: '',
    memo: '誕生日：5月15日',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-6',
    name: '渡辺 隆',
    ruby: 'わたなべ たかし',
    nickname: 'わたさん',
    designatedCastIds: ['cast-2'],
    isAlert: false,
    alertReason: '',
    memo: '接待利用が多い。領収書必須。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-7',
    name: '中村 浩二',
    ruby: 'なかむら こうじ',
    nickname: 'こうちゃん',
    designatedCastIds: ['cast-4'],
    isAlert: false,
    alertReason: '',
    memo: 'ビール党。焼酎も可。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-8',
    name: '小林 正樹',
    ruby: 'こばやし まさき',
    nickname: 'まーくん',
    designatedCastIds: ['cast-5'],
    isAlert: false,
    alertReason: '',
    memo: '毎月第一金曜来店。',
    linkedCustomerIds: ['customer-9'],
    lastVisitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-9',
    name: '加藤 雄介',
    ruby: 'かとう ゆうすけ',
    nickname: 'ゆうすけ',
    designatedCastIds: ['cast-5'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: ['customer-8'],
    lastVisitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-10',
    name: '吉田 康夫',
    ruby: 'よしだ やすお',
    nickname: 'やっさん',
    designatedCastIds: ['cast-6'],
    isAlert: false,
    alertReason: '',
    memo: '日本酒専門。純米大吟醸のみ。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-11',
    name: '松本 哲也',
    ruby: 'まつもと てつや',
    nickname: 'てっちゃん',
    designatedCastIds: ['cast-7'],
    isAlert: false,
    alertReason: '',
    memo: 'ゴルフ好き。接待多め。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-12',
    name: '井上 修一',
    ruby: 'いのうえ しゅういち',
    nickname: 'しゅーさん',
    designatedCastIds: ['cast-3', 'cast-8'],
    isAlert: false,
    alertReason: '',
    memo: '誕生日：11月3日。ブランデー好き。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-13',
    name: '木村 俊介',
    ruby: 'きむら しゅんすけ',
    nickname: 'しゅんちゃん',
    designatedCastIds: ['cast-9'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-14',
    name: '林 大地',
    ruby: 'はやし だいち',
    nickname: 'だいちゃん',
    designatedCastIds: ['cast-10'],
    isAlert: true,
    alertReason: '過去に他のお客様とトラブルあり。座席配置に注意。',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-15',
    name: '清水 義雄',
    ruby: 'しみず よしお',
    nickname: 'よっちゃん',
    designatedCastIds: ['cast-11'],
    isAlert: false,
    alertReason: '',
    memo: 'ワイン専門。フランス産のみ。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-16',
    name: '橋本 信二',
    ruby: 'はしもと しんじ',
    nickname: 'しんちゃん',
    designatedCastIds: ['cast-12'],
    isAlert: false,
    alertReason: '',
    memo: '早めの時間帯希望。21時には退席。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-17',
    name: '岡田 光雄',
    ruby: 'おかだ みつお',
    nickname: 'みっちゃん',
    designatedCastIds: ['cast-13'],
    isAlert: false,
    alertReason: '',
    memo: '静かな席希望。カウンター禁止。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-18',
    name: '前田 竜也',
    ruby: 'まえだ たつや',
    nickname: 'りゅうちゃん',
    designatedCastIds: ['cast-14'],
    isAlert: false,
    alertReason: '',
    memo: 'スコッチウィスキー党。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-19',
    name: '藤田 宗一郎',
    ruby: 'ふじた そういちろう',
    nickname: 'ふじちゃん',
    designatedCastIds: ['cast-15'],
    isAlert: false,
    alertReason: '',
    memo: '誕生日：8月20日。シャンパン好き。',
    linkedCustomerIds: ['customer-20'],
    lastVisitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-20',
    name: '西村 隼人',
    ruby: 'にしむら はやと',
    nickname: 'はやちゃん',
    designatedCastIds: ['cast-16'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: ['customer-19'],
    lastVisitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-21',
    name: '高橋 健一',
    ruby: 'たかはし けんいち',
    nickname: 'けんさん',
    designatedCastIds: ['cast-4'],
    isAlert: false,
    alertReason: '',
    memo: 'テキーラ好み。ショットで飲む。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-22',
    name: '村上 浩',
    ruby: 'むらかみ ひろし',
    nickname: 'むーさん',
    designatedCastIds: ['cast-17'],
    isAlert: false,
    alertReason: '',
    memo: '常連。毎週土曜来店。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-23',
    name: '阿部 浩司',
    ruby: 'あべ こうじ',
    nickname: 'あべちゃん',
    designatedCastIds: ['cast-18'],
    isAlert: false,
    alertReason: '',
    memo: 'お酒弱め。ソフトドリンク多め。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-24',
    name: '石川 昌弘',
    ruby: 'いしかわ まさひろ',
    nickname: 'まさちゃん',
    designatedCastIds: ['cast-1'],
    isAlert: false,
    alertReason: '',
    memo: '',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-25',
    name: '上田 昭二',
    ruby: 'うえだ しょうじ',
    nickname: 'うえちゃん',
    designatedCastIds: ['cast-19'],
    isAlert: false,
    alertReason: '',
    memo: '経営者。大人数での来店多い。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  {
    id: 'customer-26',
    name: '河野 充',
    ruby: 'かわの みつる',
    nickname: 'みつさん',
    designatedCastIds: ['cast-20'],
    isAlert: false,
    alertReason: '',
    memo: 'ウォッカカクテル好き。',
    linkedCustomerIds: [],
    lastVisitDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    isFavorite: false,
    hasGlass: false,
    glassMemo: '',
    receiptNames: [],
    phone: '',
    email: '',
    updatedBy: '',
  },
  { id: 'customer-27', name: '坂本 龍一', ruby: 'さかもと りゅういち', nickname: 'りゅうさん', designatedCastIds: ['cast-24'], isAlert: false, alertReason: '', memo: 'ジャズ好き。静かな席希望。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-28', name: '長谷川 誠', ruby: 'はせがわ まこと', nickname: 'はせさん', designatedCastIds: ['cast-25'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['長谷川建設'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-29', name: '石田 雄太', ruby: 'いしだ ゆうた', nickname: 'ゆうくん', designatedCastIds: ['cast-26'], isAlert: false, alertReason: '', memo: '赤ワイン好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'クリスタルグラス・棚2番', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-30', name: '原田 浩司', ruby: 'はらだ こうじ', nickname: 'こうちゃん', designatedCastIds: ['cast-27'], isAlert: false, alertReason: '', memo: '月2回ペースで来店。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-31', name: '藤井 雅人', ruby: 'ふじい まさと', nickname: 'ふじさん', designatedCastIds: ['cast-28'], isAlert: false, alertReason: '', memo: 'スコッチ好み。静かに飲む。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-32', name: '中川 健', ruby: 'なかがわ けん', nickname: 'けんちゃん', designatedCastIds: ['cast-29'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-33', name: '小川 哲也', ruby: 'おがわ てつや', nickname: 'てつさん', designatedCastIds: ['cast-30'], isAlert: false, alertReason: '', memo: '誕生日：3月12日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-34', name: '三浦 大輔', ruby: 'みうら だいすけ', nickname: 'みうちゃん', designatedCastIds: ['cast-31'], isAlert: false, alertReason: '', memo: 'バーボン専門。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-35', name: '斎藤 光', ruby: 'さいとう ひかる', nickname: 'ひかるさん', designatedCastIds: ['cast-32'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'タンブラー・棚5番', receiptNames: ['斎藤商事'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-36', name: '池田 勇', ruby: 'いけだ いさむ', nickname: 'いけちゃん', designatedCastIds: ['cast-33'], isAlert: false, alertReason: '', memo: 'シャンパン好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-37', name: '山口 浩', ruby: 'やまぐち ひろし', nickname: 'やまさん', designatedCastIds: ['cast-1', 'cast-24'], isAlert: false, alertReason: '', memo: 'VIP。毎月大口来店。', linkedCustomerIds: ['customer-38'], lastVisitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['山口産業株式会社'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-38', name: '松田 隆', ruby: 'まつだ たかし', nickname: 'まつさん', designatedCastIds: ['cast-2'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: ['customer-37'], lastVisitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-39', name: '野村 康介', ruby: 'のむら こうすけ', nickname: 'のむさん', designatedCastIds: ['cast-3'], isAlert: false, alertReason: '', memo: '焼酎好み。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-40', name: '遠藤 裕之', ruby: 'えんどう ひろゆき', nickname: 'えんちゃん', designatedCastIds: ['cast-4'], isAlert: true, alertReason: '過去に支払い遅延あり。前払い推奨。', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-41', name: '内田 修', ruby: 'うちだ おさむ', nickname: 'うちさん', designatedCastIds: ['cast-5'], isAlert: false, alertReason: '', memo: '日本酒・焼酎どちらも好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-42', name: '安藤 雄一', ruby: 'あんどう ゆういち', nickname: 'あんちゃん', designatedCastIds: ['cast-6'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-43', name: '岩田 巧', ruby: 'いわた たくみ', nickname: 'たくちゃん', designatedCastIds: ['cast-7'], isAlert: false, alertReason: '', memo: 'クラフトビール好み。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-44', name: '金子 達也', ruby: 'かねこ たつや', nickname: 'かねちゃん', designatedCastIds: ['cast-8'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-45', name: '丸山 直樹', ruby: 'まるやま なおき', nickname: 'まるちゃん', designatedCastIds: ['cast-9'], isAlert: false, alertReason: '', memo: '誕生日：6月30日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'ロックグラス・棚8番', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-46', name: '横山 一成', ruby: 'よこやま かずなり', nickname: 'よこさん', designatedCastIds: ['cast-10'], isAlert: false, alertReason: '', memo: 'ウィスキー全般OK。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-47', name: '宮崎 浩二', ruby: 'みやざき こうじ', nickname: 'みやちゃん', designatedCastIds: ['cast-11'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['宮崎商会'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-48', name: '菊池 俊', ruby: 'きくち しゅん', nickname: 'きくちゃん', designatedCastIds: ['cast-12'], isAlert: false, alertReason: '', memo: 'テキーラ好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-49', name: '今井 達夫', ruby: 'いまい たつお', nickname: 'いまさん', designatedCastIds: ['cast-13'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-50', name: '永田 信也', ruby: 'ながた しんや', nickname: 'ながちゃん', designatedCastIds: ['cast-14'], isAlert: false, alertReason: '', memo: '接待利用多め。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['永田物産'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-51', name: '浜田 義弘', ruby: 'はまだ よしひろ', nickname: 'はまちゃん', designatedCastIds: ['cast-15'], isAlert: false, alertReason: '', memo: 'カクテル好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-52', name: '大野 裕', ruby: 'おおの ゆたか', nickname: 'おおのさん', designatedCastIds: ['cast-16'], isAlert: false, alertReason: '', memo: 'シングルモルト好み。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'マイグラス・棚1番', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-53', name: '柴田 誠一', ruby: 'しばた せいいち', nickname: 'しばちゃん', designatedCastIds: ['cast-17'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-54', name: '桑原 健二', ruby: 'くわはら けんじ', nickname: 'くわちゃん', designatedCastIds: ['cast-18'], isAlert: false, alertReason: '', memo: '誕生日：10月5日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 49 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-55', name: '田村 武司', ruby: 'たむら たけし', nickname: 'たむちゃん', designatedCastIds: ['cast-19'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-56', name: '大森 隼', ruby: 'おおもり はやと', nickname: 'おおもりさん', designatedCastIds: ['cast-20'], isAlert: false, alertReason: '', memo: 'グレーンウィスキー好み。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-57', name: '上野 哲夫', ruby: 'うえの てつお', nickname: 'うえのさん', designatedCastIds: ['cast-21'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 65 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-58', name: '吉川 誠', ruby: 'よしかわ まこと', nickname: 'よしちゃん', designatedCastIds: ['cast-22'], isAlert: false, alertReason: '', memo: '水割り専門。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-59', name: '植田 一郎', ruby: 'うえだ いちろう', nickname: 'うえちゃん2', designatedCastIds: ['cast-23'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 31 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-60', name: '奥田 亮', ruby: 'おくだ りょう', nickname: 'りょうさん', designatedCastIds: ['cast-24'], isAlert: false, alertReason: '', memo: 'ラム好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-61', name: '谷口 豊', ruby: 'たにぐち ゆたか', nickname: 'たにちゃん', designatedCastIds: ['cast-25'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-62', name: '後藤 博明', ruby: 'ごとう ひろあき', nickname: 'ごっちゃん', designatedCastIds: ['cast-26'], isAlert: true, alertReason: '大声で騒ぐことがある。注意が必要。', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-63', name: '杉山 聡', ruby: 'すぎやま さとし', nickname: 'すぎちゃん', designatedCastIds: ['cast-27'], isAlert: false, alertReason: '', memo: 'ノンアルコール可。食事メイン。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-64', name: '西田 徹', ruby: 'にしだ とおる', nickname: 'にしちゃん', designatedCastIds: ['cast-28'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 53 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-65', name: '黒田 隆司', ruby: 'くろだ りゅうじ', nickname: 'くろちゃん', designatedCastIds: ['cast-29'], isAlert: false, alertReason: '', memo: '誕生日：1月25日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-66', name: '土屋 英樹', ruby: 'つちや ひでき', nickname: 'つちちゃん', designatedCastIds: ['cast-30'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-67', name: '平野 大輔', ruby: 'ひらの だいすけ', nickname: 'ひらちゃん', designatedCastIds: ['cast-31'], isAlert: false, alertReason: '', memo: 'ブランデー好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'ワイングラス・棚4番', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-68', name: '北村 直也', ruby: 'きたむら なおや', nickname: 'きたちゃん', designatedCastIds: ['cast-32'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['北村工業'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-69', name: '服部 和夫', ruby: 'はっとり かずお', nickname: 'はっちゃん', designatedCastIds: ['cast-33'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 47 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-70', name: '川島 勝', ruby: 'かわしま まさる', nickname: 'かわちゃん', designatedCastIds: ['cast-1', 'cast-26'], isAlert: false, alertReason: '', memo: 'VIP。シャンパン中心。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['川島ホールディングス'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-71', name: '竹内 洋介', ruby: 'たけうち ようすけ', nickname: 'たけちゃん', designatedCastIds: ['cast-2', 'cast-25'], isAlert: false, alertReason: '', memo: 'ハイボール好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-72', name: '福田 孝之', ruby: 'ふくだ たかゆき', nickname: 'ふくちゃん', designatedCastIds: ['cast-3'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 62 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-73', name: '鎌田 晴彦', ruby: 'かまだ はるひこ', nickname: 'かまちゃん', designatedCastIds: ['cast-4'], isAlert: false, alertReason: '', memo: 'ジン好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-74', name: '河合 雅之', ruby: 'かわい まさゆき', nickname: 'かわいさん', designatedCastIds: ['cast-5'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 34 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-75', name: '武田 拓也', ruby: 'たけだ たくや', nickname: 'たけだくん', designatedCastIds: ['cast-6'], isAlert: false, alertReason: '', memo: '誕生日：7月19日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-76', name: '加藤 勝彦', ruby: 'かとう かつひこ', nickname: 'かつさん', designatedCastIds: ['cast-7'], isAlert: false, alertReason: '', memo: 'ジャパニーズウィスキー好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-77', name: '松本 雄介', ruby: 'まつもと ゆうすけ', nickname: 'まつゆう', designatedCastIds: ['cast-8'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 43 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-78', name: '高木 義人', ruby: 'たかぎ よしと', nickname: 'たかぎさん', designatedCastIds: ['cast-9'], isAlert: false, alertReason: '', memo: 'ワイン全般好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'ワイングラス・棚7番', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-79', name: '庄司 広志', ruby: 'しょうじ ひろし', nickname: 'しょうちゃん', designatedCastIds: ['cast-10'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 57 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-80', name: '吉田 文雄', ruby: 'よしだ ふみお', nickname: 'ふみさん', designatedCastIds: ['cast-11'], isAlert: false, alertReason: '', memo: '接待専門。領収書必須。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['吉田コーポレーション'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-81', name: '辻 正道', ruby: 'つじ まさみち', nickname: 'つじさん', designatedCastIds: ['cast-12'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-82', name: '尾崎 浩之', ruby: 'おざき ひろゆき', nickname: 'おざちゃん', designatedCastIds: ['cast-13'], isAlert: false, alertReason: '', memo: 'テキーラショット好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-83', name: '水野 俊之', ruby: 'みずの としゆき', nickname: 'みずちゃん', designatedCastIds: ['cast-14'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-84', name: '川口 明', ruby: 'かわぐち あきら', nickname: 'あきさん', designatedCastIds: ['cast-15'], isAlert: false, alertReason: '', memo: '誕生日：9月3日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 51 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-85', name: '田口 元', ruby: 'たぐち はじめ', nickname: 'はじさん', designatedCastIds: ['cast-16'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-86', name: '宮本 浩', ruby: 'みやもと ひろし', nickname: 'みやちゃん2', designatedCastIds: ['cast-17'], isAlert: false, alertReason: '', memo: 'ロック専門。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-87', name: '栗原 義明', ruby: 'くりはら よしあき', nickname: 'くりちゃん', designatedCastIds: ['cast-18'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-88', name: '橋口 弘毅', ruby: 'はしぐち こうき', nickname: 'はしちゃん', designatedCastIds: ['cast-19'], isAlert: false, alertReason: '', memo: '日本酒専門。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-89', name: '島田 賢一', ruby: 'しまだ けんいち', nickname: 'しまちゃん', designatedCastIds: ['cast-20'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-90', name: '成田 光男', ruby: 'なりた みつお', nickname: 'なりちゃん', designatedCastIds: ['cast-21'], isAlert: false, alertReason: '', memo: 'シャンパン・ワイン好み。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-91', name: '森田 悟', ruby: 'もりた さとる', nickname: 'もりちゃん', designatedCastIds: ['cast-22'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 71 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-92', name: '小田 俊男', ruby: 'おだ としお', nickname: 'おだちゃん', designatedCastIds: ['cast-23'], isAlert: false, alertReason: '', memo: '焼酎水割り好き。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-93', name: '久保 和也', ruby: 'くぼ かずや', nickname: 'くぼちゃん', designatedCastIds: ['cast-24'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-94', name: '篠原 孝', ruby: 'しのはら たかし', nickname: 'しのちゃん', designatedCastIds: ['cast-25'], isAlert: false, alertReason: '', memo: 'VIP常連。週1来店。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: true, glassMemo: 'クリスタル・棚3番', receiptNames: ['篠原グループ'], phone: '', email: '', updatedBy: '' },
  { id: 'customer-95', name: '古川 裕太', ruby: 'ふるかわ ゆうた', nickname: 'ふるちゃん', designatedCastIds: ['cast-26'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 58 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-96', name: '秋山 義雄', ruby: 'あきやま よしお', nickname: 'あきちゃん', designatedCastIds: ['cast-27'], isAlert: false, alertReason: '', memo: 'ハイボール専門。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-97', name: '津田 正一', ruby: 'つだ しょういち', nickname: 'つだちゃん', designatedCastIds: ['cast-28'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 46 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-98', name: '下村 浩二', ruby: 'しもむら こうじ', nickname: 'しもちゃん', designatedCastIds: ['cast-29'], isAlert: false, alertReason: '', memo: '誕生日：12月24日。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-99', name: '矢野 勉', ruby: 'やの つとむ', nickname: 'やのちゃん', designatedCastIds: ['cast-30'], isAlert: false, alertReason: '', memo: '', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: [], phone: '', email: '', updatedBy: '' },
  { id: 'customer-100', name: '本田 一男', ruby: 'ほんだ かずお', nickname: 'ほんちゃん', designatedCastIds: ['cast-31', 'cast-32'], isAlert: false, alertReason: '', memo: 'VIP。シャンパンタワー経験あり。', linkedCustomerIds: [], lastVisitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), updatedAt: new Date().toISOString(), isFavorite: false, hasGlass: false, glassMemo: '', receiptNames: ['本田ホールディングス'], phone: '', email: '', updatedBy: '' },
]

export const mockBottles: Bottle[] = [
  {
    id: 'bottle-1',
    customerId: 'customer-1',
    name: 'ドンペリニヨン 2015',
    remaining: '100%',
    openedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-2',
    customerId: 'customer-1',
    name: 'バランタイン 17年',
    remaining: '50%',
    openedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-3',
    customerId: 'customer-1',
    name: 'ヘネシー XO',
    remaining: '10%',
    openedDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-4',
    customerId: 'customer-2',
    name: 'シーバスリーガル 18年',
    remaining: '75%',
    openedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-5',
    customerId: 'customer-4',
    name: 'サントリー響 21年',
    remaining: '30%',
    openedDate: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-6',
    customerId: 'customer-5',
    name: 'ジョニーウォーカー ブルーラベル',
    remaining: '100%',
    openedDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-7',
    customerId: 'customer-6',
    name: 'モエ・エ・シャンドン',
    remaining: '100%',
    openedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-8',
    customerId: 'customer-7',
    name: '山崎 12年',
    remaining: '60%',
    openedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-9',
    customerId: 'customer-8',
    name: 'マッカラン 18年',
    remaining: '80%',
    openedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-10',
    customerId: 'customer-10',
    name: '獺祭 二割三分',
    remaining: '50%',
    openedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-11',
    customerId: 'customer-12',
    name: 'レミーマルタン XO',
    remaining: '70%',
    openedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-12',
    customerId: 'customer-15',
    name: 'ペトリュス 2018',
    remaining: '100%',
    openedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-13',
    customerId: 'customer-16',
    name: 'ベルヴェデール ウォッカ',
    remaining: '40%',
    openedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-14',
    customerId: 'customer-18',
    name: 'グレンリベット 18年',
    remaining: '25%',
    openedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-15',
    customerId: 'customer-19',
    name: 'クリュッグ グランド キュヴェ',
    remaining: '100%',
    openedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'bottle-16',
    customerId: 'customer-22',
    name: 'アードベッグ 10年',
    remaining: '85%',
    openedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  { id: 'bottle-17', customerId: 'customer-27', name: '竹鶴 17年', remaining: '70%', openedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-18', customerId: 'customer-29', name: 'シャトー・マルゴー 2017', remaining: '50%', openedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-19', customerId: 'customer-29', name: 'オーパスワン 2019', remaining: '100%', openedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-20', customerId: 'customer-32', name: 'ボウモア 15年', remaining: '40%', openedDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-21', customerId: 'customer-34', name: 'ワイルドターキー 12年', remaining: '60%', openedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-22', customerId: 'customer-35', name: 'グレンフィディック 18年', remaining: '90%', openedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-23', customerId: 'customer-36', name: 'ローラン・ペリエ ロゼ', remaining: '100%', openedDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-24', customerId: 'customer-37', name: 'ドンペリニヨン ロゼ 2013', remaining: '100%', openedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-25', customerId: 'customer-37', name: '山崎 18年', remaining: '35%', openedDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-26', customerId: 'customer-42', name: 'ラフロイグ 10年', remaining: '65%', openedDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-27', customerId: 'customer-44', name: 'タリスカー 10年', remaining: '80%', openedDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-28', customerId: 'customer-45', name: 'グレンモーレンジ 18年', remaining: '55%', openedDate: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-29', customerId: 'customer-47', name: 'シーバスリーガル 25年', remaining: '45%', openedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-30', customerId: 'customer-50', name: 'バランタイン 21年', remaining: '75%', openedDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-31', customerId: 'customer-52', name: 'グレンリベット 25年', remaining: '90%', openedDate: new Date(Date.now() - 37 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-32', customerId: 'customer-56', name: 'カナディアンクラブ 20年', remaining: '60%', openedDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-33', customerId: 'customer-58', name: 'サントリー白州 12年', remaining: '30%', openedDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-34', customerId: 'customer-60', name: 'ロン・サカパ 23年', remaining: '85%', openedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-35', customerId: 'customer-63', name: 'ペリエジュエ ベル エポック', remaining: '100%', openedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-36', customerId: 'customer-67', name: 'レミーマルタン ルイ13世', remaining: '20%', openedDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-37', customerId: 'customer-70', name: 'クリスタル 2015', remaining: '100%', openedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-38', customerId: 'customer-70', name: 'アルマンド ブリニャック', remaining: '50%', openedDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-39', customerId: 'customer-71', name: '響 JAPANESE HARMONY', remaining: '70%', openedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-40', customerId: 'customer-76', name: '余市 10年', remaining: '45%', openedDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-41', customerId: 'customer-78', name: 'シャトー・ラフィット 2016', remaining: '100%', openedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-42', customerId: 'customer-80', name: 'バランタイン 30年', remaining: '55%', openedDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-43', customerId: 'customer-87', name: '伊佐美', remaining: '80%', openedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-44', customerId: 'customer-88', name: '黒龍 特吟', remaining: '65%', openedDate: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-45', customerId: 'customer-90', name: 'モエ・エ・シャンドン ネクター', remaining: '100%', openedDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-46', customerId: 'customer-94', name: 'ドンペリニヨン 2012', remaining: '30%', openedDate: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-47', customerId: 'customer-94', name: 'アルマンド ゴールド', remaining: '100%', openedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-48', customerId: 'customer-100', name: 'クリスタル ロゼ 2014', remaining: '100%', openedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'bottle-49', customerId: 'customer-100', name: 'ルイ・ロデレール ブリュット', remaining: '60%', openedDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString() },
]

export const mockVisitRecords: VisitRecord[] = [
  {
    id: 'visit-1',
    customerId: 'customer-1',
    visitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-1'],
    inStoreCastIds: ['cast-2'],
    bottlesOpened: ['bottle-1'],
    bottlesUsed: ['bottle-2'],
    memo: 'ドンペリ開封。大変ご機嫌でした。',
  },
  {
    id: 'visit-2',
    customerId: 'customer-1',
    visitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-1'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-2'],
    bottlesUsed: ['bottle-3'],
    memo: 'バランタイン開封。',
  },
  {
    id: 'visit-3',
    customerId: 'customer-2',
    visitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-2'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-4'],
    bottlesUsed: [],
    memo: '',
  },
  {
    id: 'visit-4',
    customerId: 'customer-4',
    visitDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-1'],
    inStoreCastIds: ['cast-3'],
    bottlesOpened: [],
    bottlesUsed: ['bottle-5'],
    memo: '響を使用。',
  },
  {
    id: 'visit-5',
    customerId: 'customer-5',
    visitDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-3'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-6'],
    bottlesUsed: [],
    memo: 'ブルーラベル開封。誕生日のお祝い。',
  },
  {
    id: 'visit-6',
    customerId: 'customer-6',
    visitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-2'],
    inStoreCastIds: ['cast-1'],
    bottlesOpened: ['bottle-7'],
    bottlesUsed: [],
    memo: '接待利用。領収書発行済。',
  },
  {
    id: 'visit-7',
    customerId: 'customer-7',
    visitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-4'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-8'],
    bottlesUsed: [],
    memo: '山崎開封。',
  },
  {
    id: 'visit-8',
    customerId: 'customer-8',
    visitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-5'],
    inStoreCastIds: ['cast-6'],
    bottlesOpened: ['bottle-9'],
    bottlesUsed: [],
    memo: '小林様・加藤様ご一緒に来店。',
  },
  {
    id: 'visit-9',
    customerId: 'customer-10',
    visitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-6'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-10'],
    bottlesUsed: [],
    memo: '獺祭開封。日本酒の話で盛り上がり。',
  },
  {
    id: 'visit-10',
    customerId: 'customer-12',
    visitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-3', 'cast-8'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-11'],
    bottlesUsed: [],
    memo: 'XO開封。',
  },
  {
    id: 'visit-11',
    customerId: 'customer-16',
    visitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-12'],
    inStoreCastIds: [],
    bottlesOpened: ['bottle-13'],
    bottlesUsed: [],
    memo: '早めにお帰り。',
  },
  {
    id: 'visit-12',
    customerId: 'customer-22',
    visitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    designatedCastIds: ['cast-17'],
    inStoreCastIds: ['cast-18'],
    bottlesOpened: ['bottle-16'],
    bottlesUsed: [],
    memo: '毎週来店。今週も楽しんでいただいた。',
  },
  { id: 'visit-13', customerId: 'customer-27', visitDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-24'], inStoreCastIds: ['cast-25'], bottlesOpened: ['bottle-17'], bottlesUsed: [], memo: '竹鶴開封。ジャズの話で盛り上がり。' },
  { id: 'visit-14', customerId: 'customer-29', visitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-26'], inStoreCastIds: ['cast-27'], bottlesOpened: ['bottle-18'], bottlesUsed: [], memo: 'マルゴー開封。' },
  { id: 'visit-15', customerId: 'customer-29', visitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-26'], inStoreCastIds: [], bottlesOpened: ['bottle-19'], bottlesUsed: ['bottle-18'], memo: 'オーパスワン開封。' },
  { id: 'visit-16', customerId: 'customer-32', visitDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-29'], inStoreCastIds: ['cast-30'], bottlesOpened: ['bottle-20'], bottlesUsed: [], memo: '' },
  { id: 'visit-17', customerId: 'customer-32', visitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-29'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-20'], memo: '残量少なめ。' },
  { id: 'visit-18', customerId: 'customer-34', visitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-31'], inStoreCastIds: ['cast-32'], bottlesOpened: ['bottle-21'], bottlesUsed: [], memo: 'ターキー開封。' },
  { id: 'visit-19', customerId: 'customer-35', visitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-32'], inStoreCastIds: ['cast-33'], bottlesOpened: ['bottle-22'], bottlesUsed: [], memo: 'グレンフィディック開封。' },
  { id: 'visit-20', customerId: 'customer-37', visitDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-1'], inStoreCastIds: ['cast-24', 'cast-25'], bottlesOpened: ['bottle-25'], bottlesUsed: [], memo: '山崎開封。大人数での来店。' },
  { id: 'visit-21', customerId: 'customer-37', visitDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-1', 'cast-24'], inStoreCastIds: ['cast-26'], bottlesOpened: ['bottle-24'], bottlesUsed: ['bottle-25'], memo: 'ドンペリロゼ開封。接待利用。' },
  { id: 'visit-22', customerId: 'customer-42', visitDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-6'], inStoreCastIds: ['cast-7'], bottlesOpened: ['bottle-26'], bottlesUsed: [], memo: 'ラフロイグ開封。' },
  { id: 'visit-23', customerId: 'customer-44', visitDate: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-8'], inStoreCastIds: [], bottlesOpened: ['bottle-27'], bottlesUsed: [], memo: '' },
  { id: 'visit-24', customerId: 'customer-47', visitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-11'], inStoreCastIds: ['cast-12'], bottlesOpened: ['bottle-29'], bottlesUsed: [], memo: 'シーバス25年開封。' },
  { id: 'visit-25', customerId: 'customer-47', visitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-11'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-29'], memo: '' },
  { id: 'visit-26', customerId: 'customer-50', visitDate: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-14'], inStoreCastIds: ['cast-15'], bottlesOpened: ['bottle-30'], bottlesUsed: [], memo: '接待利用。領収書発行。' },
  { id: 'visit-27', customerId: 'customer-56', visitDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-20'], inStoreCastIds: ['cast-21'], bottlesOpened: ['bottle-32'], bottlesUsed: [], memo: '' },
  { id: 'visit-28', customerId: 'customer-58', visitDate: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-22'], inStoreCastIds: [], bottlesOpened: ['bottle-33'], bottlesUsed: [], memo: '白州開封。水割りで飲む。' },
  { id: 'visit-29', customerId: 'customer-58', visitDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-22'], inStoreCastIds: ['cast-23'], bottlesOpened: [], bottlesUsed: ['bottle-33'], memo: '' },
  { id: 'visit-30', customerId: 'customer-60', visitDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-24'], inStoreCastIds: ['cast-25', 'cast-26'], bottlesOpened: ['bottle-34'], bottlesUsed: [], memo: 'サカパ開封。' },
  { id: 'visit-31', customerId: 'customer-63', visitDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-27'], inStoreCastIds: [], bottlesOpened: ['bottle-35'], bottlesUsed: [], memo: '' },
  { id: 'visit-32', customerId: 'customer-67', visitDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-31'], inStoreCastIds: ['cast-32'], bottlesOpened: ['bottle-36'], bottlesUsed: [], memo: 'ルイ13世開封。記念の来店。' },
  { id: 'visit-33', customerId: 'customer-67', visitDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-31'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-36'], memo: 'ワイングラスで飲んでいただいた。' },
  { id: 'visit-34', customerId: 'customer-70', visitDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-1'], inStoreCastIds: ['cast-26', 'cast-27'], bottlesOpened: ['bottle-38'], bottlesUsed: [], memo: 'アルマンド開封。大型接待。' },
  { id: 'visit-35', customerId: 'customer-70', visitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-1', 'cast-26'], inStoreCastIds: ['cast-28'], bottlesOpened: ['bottle-37'], bottlesUsed: ['bottle-38'], memo: 'クリスタル開封。' },
  { id: 'visit-36', customerId: 'customer-71', visitDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-2', 'cast-25'], inStoreCastIds: ['cast-3'], bottlesOpened: ['bottle-39'], bottlesUsed: [], memo: '響開封。' },
  { id: 'visit-37', customerId: 'customer-76', visitDate: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-7'], inStoreCastIds: ['cast-8'], bottlesOpened: ['bottle-40'], bottlesUsed: [], memo: '余市開封。' },
  { id: 'visit-38', customerId: 'customer-78', visitDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-9'], inStoreCastIds: ['cast-10', 'cast-11'], bottlesOpened: ['bottle-41'], bottlesUsed: [], memo: 'ラフィット開封。ワインの話で盛り上がり。' },
  { id: 'visit-39', customerId: 'customer-80', visitDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-11'], inStoreCastIds: ['cast-12', 'cast-13'], bottlesOpened: ['bottle-42'], bottlesUsed: [], memo: 'バランタイン30年開封。接待利用。' },
  { id: 'visit-40', customerId: 'customer-80', visitDate: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-11'], inStoreCastIds: [], bottlesOpened: [], bottlesUsed: ['bottle-42'], memo: '' },
  { id: 'visit-41', customerId: 'customer-87', visitDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-18'], inStoreCastIds: ['cast-19'], bottlesOpened: ['bottle-43'], bottlesUsed: [], memo: '伊佐美開封。焼酎好きのお客様。' },
  { id: 'visit-42', customerId: 'customer-88', visitDate: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-19'], inStoreCastIds: [], bottlesOpened: ['bottle-44'], bottlesUsed: [], memo: '黒龍開封。日本酒の話で盛り上がり。' },
  { id: 'visit-43', customerId: 'customer-90', visitDate: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-21'], inStoreCastIds: ['cast-22'], bottlesOpened: ['bottle-45'], bottlesUsed: [], memo: 'モエネクター開封。' },
  { id: 'visit-44', customerId: 'customer-94', visitDate: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-25'], inStoreCastIds: ['cast-26', 'cast-27'], bottlesOpened: ['bottle-46'], bottlesUsed: [], memo: 'ドンペリ開封。週1常連様。' },
  { id: 'visit-45', customerId: 'customer-94', visitDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-25'], inStoreCastIds: ['cast-28'], bottlesOpened: ['bottle-47'], bottlesUsed: ['bottle-46'], memo: 'アルマンドゴールド開封。今週も楽しんでいただいた。' },
  { id: 'visit-46', customerId: 'customer-100', visitDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-31'], inStoreCastIds: ['cast-32', 'cast-33'], bottlesOpened: ['bottle-49'], bottlesUsed: [], memo: 'ブリュット開封。大人数来店。' },
  { id: 'visit-47', customerId: 'customer-100', visitDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), designatedCastIds: ['cast-31', 'cast-32'], inStoreCastIds: ['cast-24', 'cast-25'], bottlesOpened: ['bottle-48'], bottlesUsed: ['bottle-49'], memo: 'クリスタルロゼ開封。シャンパンタワー実施。大盛況。' },
]

// ─── Dummy Reservations (3 months: Feb–Apr 2026, no Sundays/holidays) ─────────

const _castIds = ['cast-1','cast-2','cast-3','cast-4','cast-5','cast-6','cast-7','cast-8','cast-9','cast-10','cast-11','cast-12','cast-13','cast-14','cast-15','cast-16','cast-17','cast-18','cast-19','cast-20']
const _times = ['19:00','19:30','20:00','20:30','21:00','21:30','22:00','22:30','23:00','23:30']
const _sizes = [2,2,1,3,2,2,1,4,2,2]
const _guests = ['田中','鈴木','佐藤','高橋','伊藤','渡辺','山本','中村','小林','加藤','松本','井上','木村','林','斎藤']

function _r(
  id: number, date: string, tIdx: number,
  opts?: { partyPlan?: boolean; accompanied?: boolean }
): Reservation {
  const i = id - 1
  const isNew = i % 4 === 3
  const isDesig = i % 3 === 0
  const isAccomp = opts?.accompanied ?? (i % 9 === 2)
  const isPP = opts?.partyPlan ?? false
  return {
    id: `res-${id}`,
    date,
    time: _times[tIdx % _times.length],
    partySize: _sizes[i % _sizes.length],
    hasDesignation: isDesig,
    designatedCastIds: isDesig ? [_castIds[i % _castIds.length]] : [],
    isAccompanied: isAccomp,
    accompaniedCastIds: isAccomp ? [_castIds[(i + 5) % _castIds.length]] : [],
    customerType: isNew ? 'new' : 'existing',
    customerIds: isNew ? [] : [`customer-${(i % 30) + 1}`],
    guestName: isNew ? _guests[i % _guests.length] : '',
    phone: '',
    isVisited: false,
    priceType: isPP ? 'party' : 'normal',
    partyPlanPrice: isPP ? [30000,25000,40000,35000][i % 4] : null,
    partyPlanMinutes: isPP ? [90,120,90,120][i % 4] : null,
    memo: '',
    updatedAt: `${date}T12:00:00.000Z`,
    updatedBy: 'test',
  }
}

export const mockReservations: Reservation[] = [
  // ── February 2026 ──
  _r(1,'2026-02-02',0), _r(2,'2026-02-03',2), _r(3,'2026-02-04',1), _r(4,'2026-02-05',3),
  _r(5,'2026-02-06',0), _r(6,'2026-02-06',4), _r(7,'2026-02-06',7,{partyPlan:true}),
  _r(8,'2026-02-07',1), _r(9,'2026-02-07',5), _r(10,'2026-02-07',3,{partyPlan:true}),
  _r(11,'2026-02-09',2), _r(12,'2026-02-10',0),
  _r(13,'2026-02-12',4),
  _r(14,'2026-02-13',0), _r(15,'2026-02-13',2), _r(16,'2026-02-13',6,{partyPlan:true}),
  _r(17,'2026-02-14',1), _r(18,'2026-02-14',4), _r(19,'2026-02-14',7,{partyPlan:true}),
  _r(20,'2026-02-16',0), _r(21,'2026-02-17',2), _r(22,'2026-02-18',1), _r(23,'2026-02-19',3),
  _r(24,'2026-02-20',0), _r(25,'2026-02-20',4), _r(26,'2026-02-20',8),
  _r(27,'2026-02-21',2), _r(28,'2026-02-21',5), _r(29,'2026-02-21',7,{partyPlan:true}),
  _r(30,'2026-02-24',1), _r(31,'2026-02-25',3), _r(32,'2026-02-26',0),
  _r(33,'2026-02-27',0), _r(34,'2026-02-27',4), _r(35,'2026-02-27',7),
  _r(36,'2026-02-28',1), _r(37,'2026-02-28',5), _r(38,'2026-02-28',8,{partyPlan:true}),
  // ── March 2026 ──
  _r(39,'2026-03-02',2), _r(40,'2026-03-03',0), _r(41,'2026-03-04',3), _r(42,'2026-03-05',1),
  _r(43,'2026-03-06',0), _r(44,'2026-03-06',4), _r(45,'2026-03-06',7,{partyPlan:true}),
  _r(46,'2026-03-07',1), _r(47,'2026-03-07',5), _r(48,'2026-03-07',8,{partyPlan:true}),
  _r(49,'2026-03-09',2), _r(50,'2026-03-10',0), _r(51,'2026-03-11',3), _r(52,'2026-03-12',1),
  _r(53,'2026-03-13',0), _r(54,'2026-03-13',4), _r(55,'2026-03-13',7),
  _r(56,'2026-03-14',2), _r(57,'2026-03-14',5), _r(58,'2026-03-14',8,{partyPlan:true}),
  _r(59,'2026-03-16',0), _r(60,'2026-03-17',2), _r(61,'2026-03-18',4), _r(62,'2026-03-19',1),
  _r(63,'2026-03-21',0), _r(64,'2026-03-21',4), _r(65,'2026-03-21',7,{partyPlan:true}),
  _r(66,'2026-03-23',2), _r(67,'2026-03-24',0), _r(68,'2026-03-25',3), _r(69,'2026-03-26',1),
  _r(70,'2026-03-27',0), _r(71,'2026-03-27',4), _r(72,'2026-03-27',7),
  _r(73,'2026-03-28',2), _r(74,'2026-03-28',5), _r(75,'2026-03-28',9,{partyPlan:true}),
  _r(76,'2026-03-30',0), _r(77,'2026-03-30',4), _r(78,'2026-03-31',2),
  // ── April 2026 ──
  _r(79,'2026-04-01',0), _r(80,'2026-04-02',2), _r(81,'2026-04-02',5),
  _r(82,'2026-04-03',0), _r(83,'2026-04-03',4), _r(84,'2026-04-03',8,{partyPlan:true}),
  _r(85,'2026-04-04',2), _r(86,'2026-04-04',5), _r(87,'2026-04-04',8,{partyPlan:true}),
  _r(88,'2026-04-06',1), _r(89,'2026-04-07',3), _r(90,'2026-04-08',0), _r(91,'2026-04-09',2),
  _r(92,'2026-04-10',0), _r(93,'2026-04-10',4), _r(94,'2026-04-10',7,{partyPlan:true}),
  _r(95,'2026-04-11',1), _r(96,'2026-04-11',5), _r(97,'2026-04-11',8,{partyPlan:true}),
  _r(98,'2026-04-13',2), _r(99,'2026-04-14',0), _r(100,'2026-04-15',3), _r(101,'2026-04-16',1),
  _r(102,'2026-04-17',0), _r(103,'2026-04-17',4), _r(104,'2026-04-17',7),
  _r(105,'2026-04-18',2), _r(106,'2026-04-18',5), _r(107,'2026-04-18',9,{partyPlan:true}),
  _r(108,'2026-04-20',0), _r(109,'2026-04-21',2), _r(110,'2026-04-22',4), _r(111,'2026-04-23',1),
  _r(112,'2026-04-24',0), _r(113,'2026-04-24',4), _r(114,'2026-04-24',7),
  _r(115,'2026-04-25',2), _r(116,'2026-04-25',5), _r(117,'2026-04-25',8,{partyPlan:true}),
  _r(118,'2026-04-27',0), _r(119,'2026-04-28',2), _r(120,'2026-04-30',4),
]
