import { createPagesFunctionHandler } from '@react-router/cloudflare'
// @ts-ignore - generated by react-router build
import * as build from '../build/server'

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => {
    const env = context.env as Record<string, string | undefined>
    // Pages Secret は process.env に入らない。
    // globalThis 経由で db.server.ts に渡す（Workers では globalThis は書き込み可能）。
    if (env.DATABASE_URL) {
      (globalThis as Record<string, unknown>).DATABASE_URL = env.DATABASE_URL
    }
    return { cloudflare: env }
  },
})
