import { createPagesFunctionHandler } from '@react-router/cloudflare'
// @ts-ignore - generated by react-router build
import * as build from '../build/server'

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => {
    const env = context.env as Record<string, string | undefined>
    console.log("getLoadContext called")
    return { cloudflare: env, supabase: null }
  },
})
