import { createPagesFunctionHandler } from '@react-router/cloudflare'
// @ts-ignore - generated by react-router build
import * as build from '../build/server'

const DATA_TABLES = new Set(['customers', 'bottles', 'casts', 'visit_records', 'reservations'])

function parseCookies(cookieHeader: string): Record<string, string> {
  return Object.fromEntries(
    cookieHeader.split(';').map((c) => c.trim()).filter(Boolean).map((c) => {
      const idx = c.indexOf('=')
      if (idx < 0) return [c, '']
      return [c.slice(0, idx).trim(), c.slice(idx + 1).trim()]
    })
  )
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function decodeJWT(token: string): Record<string, any> | null {
  try {
    const payload = token.split('.')[1]
    const decoded = atob(payload.replace(/-/g, '+').replace(/_/g, '/'))
    return JSON.parse(decoded)
  } catch {
    return null
  }
}

// Inline PostgREST client — no imports, pure fetch, works in Cloudflare Workers
function makeDbClient(supabaseUrl: string, anonKey: string, storeId?: string | null, accessToken?: string | null) {
  const restBase = `${supabaseUrl}/rest/v1`
  const token = accessToken ?? anonKey
  const h = {
    apikey: anonKey,
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  }
  class QB {
    private p = new URLSearchParams()
    private m = 'GET'
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    private b: any = undefined
    private pref: string[] = []
    private s = false; private ms = false; private head = false; private cnt = false
    constructor(private t: string) {}
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    select(cols = '*', o?: any): this {
      if (cols !== '*') this.p.set('select', cols)
      if (o?.count === 'exact') this.cnt = true
      if (o?.head) this.head = true
      return this
    }
    eq(col: string, val: string): this { this.p.set(col, `eq.${val}`); return this }
    contains(col: string, vals: string[]): this { this.p.set(col, `cs.{${vals.join(',')}}`); return this }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    order(col: string, o?: any): this {
      const dir = o?.ascending === false ? 'desc' : 'asc'
      const cur = this.p.get('order')
      this.p.set('order', cur ? `${cur},${col}.${dir}` : `${col}.${dir}`)
      return this
    }
    single(): this { this.s = true; return this }
    maybeSingle(): this { this.ms = true; return this }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    insert(d: any): this { this.m = 'POST'; this.b = d; this.pref.push('return=representation'); return this }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    update(d: any): this { this.m = 'PATCH'; this.b = d; this.pref.push('return=representation'); return this }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    upsert(d: any): this { this.m = 'POST'; this.b = d; this.pref.push('return=representation', 'resolution=merge-duplicates'); return this }
    delete(): this { this.m = 'DELETE'; return this }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    then(resolve: any, reject: any) { this._run().then(resolve, reject) }
    private async _run() {
      try {
        // Auto-inject store_id filter for data tables on reads/updates/deletes
        if (storeId && DATA_TABLES.has(this.t) && (this.m === 'GET' || this.m === 'PATCH' || this.m === 'DELETE')) {
          if (!this.p.has('store_id')) {
            this.p.set('store_id', `eq.${storeId}`)
          }
        }
        const url = new URL(`${restBase}/${this.t}`)
        this.p.forEach((v, k) => url.searchParams.set(k, v))
        const headers: Record<string, string> = { ...h }
        const pref = [...this.pref]
        if (this.cnt) pref.push('count=exact')
        if (pref.length) headers['Prefer'] = pref.join(',')
        const res = await fetch(url.toString(), {
          method: this.head ? 'HEAD' : this.m,
          headers,
          body: this.b !== undefined ? JSON.stringify(this.b) : undefined,
        })
        if (this.head) {
          const cr = res.headers.get('Content-Range')
          return { data: null, error: null, count: cr ? parseInt(cr.split('/')[1]) : null }
        }
        if (!res.ok) return { data: null, error: new Error(`HTTP ${res.status}: ${await res.text()}`) }
        if (this.m === 'DELETE') return { data: null, error: null }
        const json = await res.json()
        if (this.s || this.ms) return { data: Array.isArray(json) ? (json[0] ?? null) : json, error: null }
        return { data: json, error: null }
      } catch (e) {
        return { data: null, error: e }
      }
    }
  }
  return { from: (t: string) => new QB(t), storeId: storeId ?? null }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const handler = createPagesFunctionHandler({
  build,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  getLoadContext: (context: any) => {
    const env = (context?.context?.cloudflare?.env ?? context?.cloudflare?.env ?? context?.env ?? {}) as Record<string, string | undefined>

    // Parse auth cookies from request
    const request: Request | undefined = context?.request ?? context?.context?.request
    const cookieHeader = request?.headers?.get('Cookie') ?? ''
    const cookies = parseCookies(cookieHeader)
    const accessToken = cookies['nm-access'] ?? null
    const storeId = cookies['nm-store'] ?? null

    // Decode JWT for userId/email
    let userId: string | null = null
    let userEmail: string | null = null
    if (accessToken) {
      const payload = decodeJWT(accessToken)
      userId = payload?.sub ?? null
      userEmail = payload?.email ?? null
    }

    const supabase = (env.SUPABASE_URL && env.SUPABASE_ANON_KEY)
      ? makeDbClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, storeId, accessToken)
      : null

    return {
      cloudflare: env,
      supabase,
      userId,
      userEmail,
      storeId,
      accessToken,
      supabaseUrl: env.SUPABASE_URL ?? null,
      anonKey: env.SUPABASE_ANON_KEY ?? null,
    }
  },
})

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const onRequest: any = handler
