// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/setup": {
    params: {};
  };
  "/api/migrate": {
    params: {};
  };
  "/api/seed-reservations": {
    params: {};
  };
  "/api/favorite": {
    params: {};
  };
  "/api/visit/:id": {
    params: {
      "id": string;
    };
  };
  "/api/reservation/:id": {
    params: {
      "id": string;
    };
  };
  "/customers": {
    params: {};
  };
  "/customers/new": {
    params: {};
  };
  "/customers/:id": {
    params: {
      "id": string;
    };
  };
  "/customers/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/customers/:id/visits/new": {
    params: {
      "id": string;
    };
  };
  "/casts": {
    params: {};
  };
  "/casts/:id": {
    params: {
      "id": string;
    };
  };
  "/casts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/reservations": {
    params: {};
  };
  "/reservations/new": {
    params: {};
  };
  "/favorites": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/logout" | "/api/setup" | "/api/migrate" | "/api/seed-reservations" | "/api/favorite" | "/api/visit/:id" | "/api/reservation/:id" | "/customers" | "/customers/new" | "/customers/:id" | "/customers/:id/edit" | "/customers/:id/visits/new" | "/casts" | "/casts/:id" | "/casts/:id/edit" | "/reservations" | "/reservations/new" | "/favorites";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/api.setup.tsx": {
    id: "routes/api.setup";
    page: "/api/setup";
  };
  "routes/api.migrate.tsx": {
    id: "routes/api.migrate";
    page: "/api/migrate";
  };
  "routes/api.seed-reservations.tsx": {
    id: "routes/api.seed-reservations";
    page: "/api/seed-reservations";
  };
  "routes/api.favorite.tsx": {
    id: "routes/api.favorite";
    page: "/api/favorite";
  };
  "routes/api.visit.$id.tsx": {
    id: "routes/api.visit.$id";
    page: "/api/visit/:id";
  };
  "routes/api.reservation.$id.tsx": {
    id: "routes/api.reservation.$id";
    page: "/api/reservation/:id";
  };
  "routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/" | "/customers" | "/customers/new" | "/customers/:id" | "/customers/:id/edit" | "/customers/:id/visits/new" | "/casts" | "/casts/:id" | "/casts/:id/edit" | "/reservations" | "/reservations/new" | "/favorites";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/customers.tsx": {
    id: "routes/customers";
    page: "/customers";
  };
  "routes/customers.new.tsx": {
    id: "routes/customers.new";
    page: "/customers/new";
  };
  "routes/customers.$id.tsx": {
    id: "routes/customers.$id";
    page: "/customers/:id";
  };
  "routes/customers.$id.edit.tsx": {
    id: "routes/customers.$id.edit";
    page: "/customers/:id/edit";
  };
  "routes/customers.$id.visits.new.tsx": {
    id: "routes/customers.$id.visits.new";
    page: "/customers/:id/visits/new";
  };
  "routes/casts.tsx": {
    id: "routes/casts";
    page: "/casts";
  };
  "routes/casts.$id.tsx": {
    id: "routes/casts.$id";
    page: "/casts/:id";
  };
  "routes/casts.$id.edit.tsx": {
    id: "routes/casts.$id.edit";
    page: "/casts/:id/edit";
  };
  "routes/reservations.tsx": {
    id: "routes/reservations";
    page: "/reservations";
  };
  "routes/reservations.new.tsx": {
    id: "routes/reservations.new";
    page: "/reservations/new";
  };
  "routes/favorites.tsx": {
    id: "routes/favorites";
    page: "/favorites";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/api.setup": typeof import("./app/routes/api.setup.tsx");
  "routes/api.migrate": typeof import("./app/routes/api.migrate.tsx");
  "routes/api.seed-reservations": typeof import("./app/routes/api.seed-reservations.tsx");
  "routes/api.favorite": typeof import("./app/routes/api.favorite.tsx");
  "routes/api.visit.$id": typeof import("./app/routes/api.visit.$id.tsx");
  "routes/api.reservation.$id": typeof import("./app/routes/api.reservation.$id.tsx");
  "routes/_auth": typeof import("./app/routes/_auth.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/customers": typeof import("./app/routes/customers.tsx");
  "routes/customers.new": typeof import("./app/routes/customers.new.tsx");
  "routes/customers.$id": typeof import("./app/routes/customers.$id.tsx");
  "routes/customers.$id.edit": typeof import("./app/routes/customers.$id.edit.tsx");
  "routes/customers.$id.visits.new": typeof import("./app/routes/customers.$id.visits.new.tsx");
  "routes/casts": typeof import("./app/routes/casts.tsx");
  "routes/casts.$id": typeof import("./app/routes/casts.$id.tsx");
  "routes/casts.$id.edit": typeof import("./app/routes/casts.$id.edit.tsx");
  "routes/reservations": typeof import("./app/routes/reservations.tsx");
  "routes/reservations.new": typeof import("./app/routes/reservations.new.tsx");
  "routes/favorites": typeof import("./app/routes/favorites.tsx");
};